using System.Text;

namespace HushNode.IntegrationTests.Infrastructure;

/// <summary>
/// Generates minimal valid PDF and video test files for E2E attachment tests.
/// Each file has a labeled name encoding sender, target, and file type
/// so test screenshots and verification can identify exactly which file
/// arrived at which recipient.
///
/// PDFs are generated as minimal valid PDF 1.0 with correct cross-reference offsets.
/// Videos use a real VP8/WebM video (1s, 160x120, blue frame) generated by ffmpeg,
/// embedded as base64. WebM/VP8 is used instead of H.264/MP4 because Playwright's
/// bundled Chromium always supports VP8 (open codec) but may lack H.264 support.
/// The browser can decode this and extract frames via canvas,
/// so the E2E test exercises the real video-thumbnail path.
/// </summary>
internal static class TestFileGenerator
{
    /// <summary>
    /// Generates a labeled PDF document and returns the file name and PDF bytes.
    /// The PDF is minimal (single blank page) but valid enough for the attachment pipeline.
    /// pdfjs-dist in the browser may or may not render the first page, but the
    /// processAttachments pipeline handles errors gracefully.
    /// </summary>
    /// <param name="senderName">Display name of sender (e.g., "Alice").</param>
    /// <param name="targetName">Display name of target (e.g., "Bob").</param>
    /// <returns>Tuple of (fileName, pdfBytes).</returns>
    public static (string FileName, byte[] PdfBytes) GenerateTestPdf(string senderName, string targetName)
    {
        var fileName = $"Test-PDF-from-{senderName}-to-{targetName}.pdf";
        var pdfBytes = BuildMinimalPdf();
        return (fileName, pdfBytes);
    }

    /// <summary>
    /// Generates a labeled video file and returns the file name and bytes.
    /// The video is a real VP8/WebM video (1s, 160x120, single blue frame)
    /// that all Chromium browsers can decode and extract frames from via canvas.
    /// WebM/VP8 is used instead of H.264/MP4 because Playwright's bundled Chromium
    /// always supports VP8 (open codec) but may lack H.264 support.
    /// </summary>
    /// <param name="senderName">Display name of sender (e.g., "Alice").</param>
    /// <param name="targetName">Display name of target (e.g., "Bob").</param>
    /// <returns>Tuple of (fileName, videoBytes).</returns>
    public static (string FileName, byte[] Mp4Bytes) GenerateTestVideo(string senderName, string targetName)
    {
        var fileName = $"Test-Video-from-{senderName}-to-{targetName}.webm";
        var videoBytes = GetRealVideoBytes();
        return (fileName, videoBytes);
    }

    /// <summary>
    /// Returns a tiny "executable" file for blocked file rejection testing.
    /// </summary>
    public static (string FileName, byte[] ExeBytes) GenerateBlockedExe()
    {
        var fileName = "program.exe";
        var exeBytes = Encoding.UTF8.GetBytes("MZ_FAKE_EXECUTABLE");
        return (fileName, exeBytes);
    }

    /// <summary>
    /// Builds a minimal valid PDF 1.0 document (single blank page, ~230 bytes).
    /// Cross-reference offsets are computed accurately.
    /// </summary>
    private static byte[] BuildMinimalPdf()
    {
        // Build the PDF body with known byte offsets
        var sb = new StringBuilder();
        sb.Append("%PDF-1.0\n");

        var obj1Offset = sb.Length;
        sb.Append("1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n");

        var obj2Offset = sb.Length;
        sb.Append("2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n");

        var obj3Offset = sb.Length;
        sb.Append("3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj\n");

        var xrefOffset = sb.Length;
        sb.Append("xref\n0 4\n");
        sb.Append("0000000000 65535 f \n");
        sb.Append($"{obj1Offset:D10} 00000 n \n");
        sb.Append($"{obj2Offset:D10} 00000 n \n");
        sb.Append($"{obj3Offset:D10} 00000 n \n");
        sb.Append("trailer<</Root 1 0 R/Size 4>>\n");
        sb.Append($"startxref\n{xrefOffset}\n%%EOF");

        return Encoding.ASCII.GetBytes(sb.ToString());
    }

    /// <summary>
    /// Real VP8/WebM video (5s, 160x120, 10fps blue frames, ~1.9KB).
    /// Generated with: ffmpeg -f lavfi -i "color=c=blue:s=160x120:d=5:r=10" -c:v libvpx -b:v 200k -t 5
    /// VP8/WebM is always supported by Chromium (including Playwright's bundled build)
    /// unlike H.264/MP4 which requires proprietary codecs.
    /// The 5s duration gives E2E tests enough time to test play/pause/seek.
    /// </summary>
    private const string RealVideoBase64 = "GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQJChYECGFOAZwEAAAAAAAccEU2bdLpNu4tTq4QVSalmU6yBoU27i1OrhBZUrmtTrIHWTbuMU6uEElTDZ1OsggEjTbuMU6uEHFO7a1OsggcG7AEAAAAAAABZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmsCrXsYMPQkBNgIxMYXZmNjIuNi4xMDNXQYxMYXZmNjIuNi4xMDNEiYhAs4gAAAAAABZUrmvIrgEAAAAAAAA/14EBc8WIcTyFLvcTxr6cgQAitZyDdW5kiIEAhoVWX1ZQOIOBASPjg4QF9eEA4JCwgaC6gXiagQJVsIRVuYEBElTDZ/tzc59jwIBnyJlFo4dFTkNPREVSRIeMTGF2ZjYyLjYuMTAzc3PWY8CLY8WIcTyFLvcTxr5nyKFFo4dFTkNPREVSRIeUTGF2YzYyLjIyLjEwMSBsaWJ2cHhnyKFFo4hEVVJBVElPTkSHkzAwOjAwOjA1LjAwMDAwMDAwMAAfQ7Z1RV3ngQCj3oEAAIDwBgCdASqgAHgAAEcIhYWIhYSIAgICdaoD+AIGk48FEJxS0qE4paVCcUtKhOKWlQnFLSoTilpUJxS0qE4paVCbAP7/TRL//FhX8WFfxYV/8WFf/PzO7cX85gCjmIEAZAARAgABEBAAGAAYWC/0AAiAgQywAKOYgQDIABECAAEQEAAYABhYL/QACICBDLAAo5iBASwAEQIAARAQABgAGFgv9AAIgIEMsACjmIEBkAARAgABEBAAGAAYWC/0AAiAgQywAKOYgQH0ABECAAEQEAAYABhYL/QACICBDLAAo5iBAlgAEQIAARAQABgAGFgv9AAIgIEMsACjmIECvAARAgABEBAUYABhYL/QACICBDLAAKOYgQMgABECAAEQEAAYABhYL/QACICBDLAAo5iBA4QAEQIAARAQABgAGFgv9AAIgIEMsACjmIED6AARAgABEBAAGAAYWC/0AAiAgQywAKOYgQRMABECAAEQEAAYABhYL/QACICBDLAAo5iBBLAAEQIAARAQABgAGFgv9AAIgIEMsACjmIEFFAARAgABEBAAGAAYWC/0AAiAgQywAKOYgQV4ABECAAEQEAAYABhYL/QACICBDLAAo5iBBdwAEQIAARAQABgAGFgv9AAIgIEMsACjmIEGQAARAgABEBAAGAAYWC/0AAiAgQywAKOYgQakABECAAEQEAAYABhYL/QACICBDLAAo5iBBwgAEQIAARAQFGAAYWC/0AAiAgQywACjmIEHbAARAgABEBAAGAAYWC/0AAiAgQywAKOYgQfQABECAAEQEAAYABhYL/QACICBDLAAo5iBCDQAEQIAARAQABgAGFgv9AAIgIEMsACjmIEImAARAgABEBAAGAAYWC/0AAiAgQywAKOYgQj8ABECAAEQEAAYABhYL/QACICBDLAAo5iBCWAAEQIAARAQABgAGFgv9AAIgIEMsACjmIEJxAARAgABEBAAGAAYWC/0AAiAgQywAKOYgQooABECAAEQEAAYABhYL/QACICBDLAAo5iBCowAEQIAARAQABgAGFgv9AAIgIEMsACjmIEK8AARAgABEBAAGAAYWC/0AAiAgQywAKOYgQtUABECAAEQEBRgAGFgv9AAIgIEMsAAo5iBC7gAEQIAARAQABgAGFgv9AAIgIEMsACjmIEMHAARAgABEBAAGAAYWC/0AAiAgQywAKOYgQyAABECAAEQEAAYABhYL/QACICBDLAAo5iBDOQAEQIAARAQABgAGFgv9AAIgIEMsACjmIENSAARAgABEBAAGAAYWC/0AAiAgQywAKOYgQ2sABECAAEQEAAYABhYL/QACICBDLAAo5iBDhAAEQIAARAQABgAGFgv9AAIgIEMsACjmIEOdAARAgABEBAAGAAYWC/0AAiAgQywAKOYgQ7YABECAAEQEAAYABhYL/QACICBDLAAo5iBDzwAEQIAARAQABgAGFgv9AAIgIEMsACjmIEPoAARAgABEBAUYABhYL/QACICBDLAAKOYgRAEABECAAEQEAAYABhYL/QACICBDLAAo5iBEGgAEQIAARAQABgAGFgv9AAIgIEMsACjmIEQzAARAgABEBAAGAAYWC/0AAiAgQywAKOYgREwABECAAEQEAAYABhYL/QACICBDLAAo5iBEZQAEQIAARAQABgAGFgv9AAIgIEMsACjmIER+AARAgABEBAAGAAYWC/0AAiAgQywAKOYgRJcABECAAEQEAAYABhYL/QACICBDLAAo5iBEsAAEQIAARAQABgAGFgv9AAIgIEMsACjmIETJAARAgABEBAAGAAYWC/0AAiAgQywABxTu2uRu4+zgQC3iveBAfGCAaPwgQM=";

    /// <summary>
    /// Returns the real WebM video bytes decoded from the embedded base64 constant.
    /// </summary>
    private static byte[] GetRealVideoBytes() => Convert.FromBase64String(RealVideoBase64);
}
