// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HushNode.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "Integration")]
    [Xunit.TraitAttribute("Category", "HushSocial")]
    [Xunit.TraitAttribute("Category", "EPIC008")]
    public partial class HushSocialServerIntegrationRulesFeature : object, Xunit.IClassFixture<HushSocialServerIntegrationRulesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "Integration",
                "HushSocial",
                "EPIC008"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "HushSocialIntegration.feature"
#line hidden
        
        public HushSocialServerIntegrationRulesFeature(HushSocialServerIntegrationRulesFeature.FixtureData fixtureData, HushNode_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "HushSocial server integration rules", "  As the HushSocial backend\r\n  I want audience, privacy, interaction, and notific" +
                    "ation contracts enforced\r\n  So that EPIC-008 behavior is deterministic and secur" +
                    "e", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
  #line hidden
#line 8
    testRunner.Given("a HushServerNode at block 5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
    testRunner.And("user \"Owner\" is registered with a personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
    testRunner.And("user \"FollowerA\" is registered with a personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 11
    testRunner.And("user \"FollowerB\" is registered with a personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
    testRunner.And("user \"FollowerC\" is registered with a personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 13
    testRunner.And("user \"GuestLikeUser\" is not authenticated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Visible close profile author follows immediately without approval queue")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Visible close profile author follows immediately without approval queue")]
        [Xunit.TraitAttribute("Category", "FEAT-084")]
        [Xunit.TraitAttribute("Category", "FEAT-085")]
        [Xunit.TraitAttribute("Category", "FEAT-090")]
        [Xunit.TraitAttribute("Category", "HS-INT-090-FOLLOW")]
        public void VisibleCloseProfileAuthorFollowsImmediatelyWithoutApprovalQueue()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-084",
                    "FEAT-085",
                    "FEAT-090",
                    "HS-INT-090-FOLLOW"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Visible close profile author follows immediately without approval queue", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 17
    testRunner.Given("Owner has HushSocial enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 18
    testRunner.And("FollowerA has HushSocial enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 19
    testRunner.And("Owner profile mode is Close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 20
    testRunner.And("Owner has created an Open post \"Visible close profile post\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 21
    testRunner.When("FollowerA opens permalink for post \"Visible close profile post\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 22
    testRunner.Then("the post content should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 23
    testRunner.When("FollowerA follows Owner via social follow contract", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 24
    testRunner.Then("the social follow response should be accepted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 25
    testRunner.And("Owner should be in FollowerA Inner Circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 26
    testRunner.And("FollowerA and Owner should have a direct chat feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Circle membership removal rotates keys immediately")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Circle membership removal rotates keys immediately")]
        [Xunit.TraitAttribute("Category", "FEAT-085")]
        [Xunit.TraitAttribute("Category", "HS-INT-085-CIRCLE-REMOVAL")]
        public void CircleMembershipRemovalRotatesKeysImmediately()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-085",
                    "HS-INT-085-CIRCLE-REMOVAL"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Circle membership removal rotates keys immediately", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 30
    testRunner.Given("Owner profile mode is Close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 31
    testRunner.And("Owner has accepted follow requests from \"FollowerA, FollowerB\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 32
    testRunner.And("Owner has created circle \"Dev Circle\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 33
    testRunner.And("Owner has added \"FollowerA, FollowerB\" to circle \"Dev Circle\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 34
    testRunner.And("Owner posts \"Initial private design note\" to circle \"Dev Circle\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 35
    testRunner.When("Owner removes FollowerB from circle \"Dev Circle\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
    testRunner.Then("key generation for circle \"Dev Circle\" should be incremented", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
    testRunner.And("FollowerB should not be able to decrypt new posts in circle \"Dev Circle\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 38
    testRunner.And("FollowerA should be able to decrypt new posts in circle \"Dev Circle\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Startup bootstrap creates inner circle and links existing chat peers")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Startup bootstrap creates inner circle and links existing chat peers")]
        [Xunit.TraitAttribute("Category", "FEAT-085")]
        [Xunit.TraitAttribute("Category", "HS-INT-085-BOOTSTRAP-LINK")]
        public void StartupBootstrapCreatesInnerCircleAndLinksExistingChatPeers()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-085",
                    "HS-INT-085-BOOTSTRAP-LINK"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Startup bootstrap creates inner circle and links existing chat peers", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 42
    testRunner.Given("Owner profile mode is Close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 43
    testRunner.And("Owner has existing chat feeds with \"FollowerA, FollowerB\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 44
    testRunner.And("Owner does not have an Inner Circle yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 45
    testRunner.When("Owner opens HushFeeds and personal feed bootstrap runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 46
    testRunner.Then("Owner Inner Circle should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 47
    testRunner.And("\"FollowerA, FollowerB\" should be members of Owner Inner Circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="New chat feed creation triggers add-members-to-inner-circle")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "New chat feed creation triggers add-members-to-inner-circle")]
        [Xunit.TraitAttribute("Category", "FEAT-085")]
        [Xunit.TraitAttribute("Category", "HS-INT-085-CHAT-ADD")]
        public void NewChatFeedCreationTriggersAdd_Members_To_Inner_Circle()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-085",
                    "HS-INT-085-CHAT-ADD"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("New chat feed creation triggers add-members-to-inner-circle", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 50
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 51
    testRunner.Given("Owner profile mode is Close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 52
    testRunner.And("Owner Inner Circle already exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 53
    testRunner.And("Owner starts a new chat feed with FollowerC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 54
    testRunner.When("FEAT-085 background sync runs after chat creation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 55
    testRunner.Then("FollowerC should be added to Owner Inner Circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 56
    testRunner.And("key generation for Owner Inner Circle should be incremented", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Duplicate inner-circle add request returns explicit duplicate without key rotatio" +
            "n")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Duplicate inner-circle add request returns explicit duplicate without key rotatio" +
            "n")]
        [Xunit.TraitAttribute("Category", "FEAT-085")]
        [Xunit.TraitAttribute("Category", "HS-INT-085-DUPLICATE-ADD")]
        public void DuplicateInner_CircleAddRequestReturnsExplicitDuplicateWithoutKeyRotation()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-085",
                    "HS-INT-085-DUPLICATE-ADD"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Duplicate inner-circle add request returns explicit duplicate without key rotatio" +
                    "n", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 59
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 60
    testRunner.Given("Owner profile mode is Close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 61
    testRunner.And("Owner Inner Circle already exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 62
    testRunner.And("Owner has accepted follow request from FollowerA", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 63
    testRunner.When("Owner tries to add \"FollowerA\" again to Owner Inner Circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 64
    testRunner.Then("FEAT-085 duplicate add response should include \"FollowerA\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 65
    testRunner.And("key generation for Owner Inner Circle should remain unchanged", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Same-block duplicate add-member requests remain deterministic")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Same-block duplicate add-member requests remain deterministic")]
        [Xunit.TraitAttribute("Category", "FEAT-085")]
        [Xunit.TraitAttribute("Category", "HS-INT-085-SAME-BLOCK-DUP")]
        public void Same_BlockDuplicateAdd_MemberRequestsRemainDeterministic()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-085",
                    "HS-INT-085-SAME-BLOCK-DUP"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Same-block duplicate add-member requests remain deterministic", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 68
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 69
    testRunner.Given("Owner profile mode is Close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 70
    testRunner.And("Owner Inner Circle already exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 71
    testRunner.When("Owner submits duplicate add-members requests for \"FollowerA\" before block indexin" +
                        "g", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 72
    testRunner.And("a block is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 73
    testRunner.Then("\"FollowerA\" should be added to Owner Inner Circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 74
    testRunner.And("FEAT-085 same-block duplicate processing should rotate Owner Inner Circle only on" +
                        "ce", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Same-block create-inner-circle for multiple owners is isolated")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Same-block create-inner-circle for multiple owners is isolated")]
        [Xunit.TraitAttribute("Category", "FEAT-085")]
        [Xunit.TraitAttribute("Category", "HS-INT-085-SAME-BLOCK-CREATE")]
        [Xunit.InlineDataAttribute("2", new string[0])]
        [Xunit.InlineDataAttribute("5", new string[0])]
        [Xunit.InlineDataAttribute("10", new string[0])]
        public void Same_BlockCreate_Inner_CircleForMultipleOwnersIsIsolated(string ownerCount, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "FEAT-085",
                    "HS-INT-085-SAME-BLOCK-CREATE"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ownerCount", ownerCount);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Same-block create-inner-circle for multiple owners is isolated", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 77
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 78
    testRunner.Given(string.Format("{0} FEAT-085 owners are registered with personal feeds", ownerCount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 79
    testRunner.When("all FEAT-085 owners submit CreateInnerCircle before block indexing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 80
    testRunner.And("a block is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 81
    testRunner.Then("all FEAT-085 owners should have exactly one Inner Circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 82
    testRunner.And("all FEAT-085 create responses should be accepted pre-indexing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Open and close post visibility is enforced by permalink access")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Open and close post visibility is enforced by permalink access")]
        [Xunit.TraitAttribute("Category", "FEAT-086")]
        [Xunit.TraitAttribute("Category", "HS-INT-086-VISIBILITY")]
        public void OpenAndClosePostVisibilityIsEnforcedByPermalinkAccess()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-086",
                    "HS-INT-086-VISIBILITY"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Open and close post visibility is enforced by permalink access", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 91
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 92
    testRunner.Given("Owner profile mode is Close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 93
    testRunner.And("Owner has accepted follow request from FollowerA", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 94
    testRunner.And("Owner has created an Open post \"Public roadmap\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 95
    testRunner.And("Owner has created a Close post \"Inner circle roadmap\" for Inner Circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 96
    testRunner.When("an unauthenticated user opens permalink for post \"Public roadmap\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 97
    testRunner.Then("the post content should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 98
    testRunner.When("FollowerC opens permalink for post \"Inner circle roadmap\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 99
    testRunner.Then("a generic denial message should be returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 100
    testRunner.And("the permalink denial contract should request access from owner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 101
    testRunner.And("no private metadata should be returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 102
    testRunner.When("FollowerA opens permalink for post \"Inner circle roadmap\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 103
    testRunner.Then("the post content should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Composer contract defaults private mode to Inner Circle with last-circle lock")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Composer contract defaults private mode to Inner Circle with last-circle lock")]
        [Xunit.TraitAttribute("Category", "FEAT-086")]
        [Xunit.TraitAttribute("Category", "HS-INT-086-COMPOSER")]
        public void ComposerContractDefaultsPrivateModeToInnerCircleWithLast_CircleLock()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-086",
                    "HS-INT-086-COMPOSER"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Composer contract defaults private mode to Inner Circle with last-circle lock", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 106
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 107
    testRunner.Given("Owner profile mode is Close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 108
    testRunner.And("Owner has accepted follow request from FollowerA", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 109
    testRunner.And("Owner Inner Circle already exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 110
    testRunner.When("Owner requests social composer contract in private mode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 111
    testRunner.Then("social composer default visibility should be private", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 112
    testRunner.And("social composer should select Owner Inner Circle by default", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 113
    testRunner.And("social composer should lock the last selected private circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 114
    testRunner.And("social composer submit should be allowed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Guest private permalink denial returns create-account CTA contract")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Guest private permalink denial returns create-account CTA contract")]
        [Xunit.TraitAttribute("Category", "FEAT-086")]
        [Xunit.TraitAttribute("Category", "HS-INT-086-GUEST-DENIAL")]
        public void GuestPrivatePermalinkDenialReturnsCreate_AccountCTAContract()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-086",
                    "HS-INT-086-GUEST-DENIAL"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Guest private permalink denial returns create-account CTA contract", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 117
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 118
    testRunner.Given("Owner profile mode is Close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 119
    testRunner.And("Owner has accepted follow request from FollowerA", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 120
    testRunner.And("Owner has created a Close post \"Guest denied private post\" for Inner Circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 121
    testRunner.When("an unauthenticated user opens permalink for post \"Guest denied private post\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 122
    testRunner.Then("the permalink denial contract should target guest account creation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 123
    testRunner.And("no private metadata should be returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Media constraints for social posts match HushFeeds limits")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Media constraints for social posts match HushFeeds limits")]
        [Xunit.TraitAttribute("Category", "FEAT-086")]
        [Xunit.TraitAttribute("Category", "HS-INT-086-MEDIA")]
        public void MediaConstraintsForSocialPostsMatchHushFeedsLimits()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-086",
                    "HS-INT-086-MEDIA"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Media constraints for social posts match HushFeeds limits", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 126
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 127
    testRunner.Given("Owner has HushSocial enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 128
    testRunner.When("Owner submits an Open post with 5 valid media attachments", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 129
    testRunner.Then("the submission should be accepted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 130
    testRunner.When("Owner submits an Open post with 6 media attachments", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 131
    testRunner.Then("the submission should be rejected with a count limit error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 132
    testRunner.When("Owner submits an Open post with a media attachment over max size", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 133
    testRunner.Then("the submission should be rejected with a size limit error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reaction privacy preserves tally without exposing per-user emoji choice on privat" +
            "e content")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Reaction privacy preserves tally without exposing per-user emoji choice on privat" +
            "e content")]
        [Xunit.TraitAttribute("Category", "FEAT-087")]
        [Xunit.TraitAttribute("Category", "HS-INT-087-REACTION-PRIVACY")]
        public void ReactionPrivacyPreservesTallyWithoutExposingPer_UserEmojiChoiceOnPrivateContent()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-087",
                    "HS-INT-087-REACTION-PRIVACY"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reaction privacy preserves tally without exposing per-user emoji choice on privat" +
                    "e content", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 136
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 137
    testRunner.Given("Owner profile mode is Close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 138
    testRunner.And("Owner has accepted follow requests from \"FollowerA, FollowerB\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 139
    testRunner.And("Owner has created a Close post \"Private sentiment test\" for Inner Circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 140
    testRunner.When("FollowerA reacts to \"Private sentiment test\" with \"thumbs_up\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 141
    testRunner.And("FollowerB reacts to \"Private sentiment test\" with \"fire\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 142
    testRunner.Then("authorized viewers should see reaction tally updates on \"Private sentiment test\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 143
    testRunner.And("the backend should not expose exact reaction choice per individual user to other " +
                        "viewers", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 144
    testRunner.When("FollowerA changes reaction on \"Private sentiment test\" to \"heart\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 145
    testRunner.Then("only one active reaction should exist for FollowerA on \"Private sentiment test\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Comments and single-level replies inherit post audience")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Comments and single-level replies inherit post audience")]
        [Xunit.TraitAttribute("Category", "FEAT-088")]
        [Xunit.TraitAttribute("Category", "HS-INT-088-COMMENTS")]
        public void CommentsAndSingle_LevelRepliesInheritPostAudience()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-088",
                    "HS-INT-088-COMMENTS"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Comments and single-level replies inherit post audience", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 148
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 149
    testRunner.Given("Owner profile mode is Close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 150
    testRunner.And("Owner has accepted follow request from FollowerA", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 151
    testRunner.And("Owner has created a Close post \"Architecture thread\" for Inner Circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 152
    testRunner.When("FollowerA comments \"Looks good\" on post \"Architecture thread\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 153
    testRunner.And("Owner replies \"Thanks\" to comment \"Looks good\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 154
    testRunner.And("Owner reacts to comment \"Looks good\" with \"thumbs_up\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 155
    testRunner.And("FollowerA reacts to reply \"Thanks\" with \"heart\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 156
    testRunner.Then("FollowerA should see comment \"Looks good\" and reply \"Thanks\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 157
    testRunner.And("authorized viewers should see reaction tally updates on comment \"Looks good\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 158
    testRunner.And("authorized viewers should see reaction tally updates on reply \"Thanks\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 159
    testRunner.When("FollowerC opens post \"Architecture thread\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 160
    testRunner.Then("FollowerC should receive access denied for post comments", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 161
    testRunner.And("FollowerC should receive access denied for post replies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Guest interaction contracts require auth while preserving public readability")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Guest interaction contracts require auth while preserving public readability")]
        [Xunit.TraitAttribute("Category", "FEAT-089")]
        [Xunit.TraitAttribute("Category", "HS-INT-089-GUEST-CTA")]
        public void GuestInteractionContractsRequireAuthWhilePreservingPublicReadability()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-089",
                    "HS-INT-089-GUEST-CTA"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Guest interaction contracts require auth while preserving public readability", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 164
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 165
    testRunner.Given("Owner has created an Open post \"Public onboarding post\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 166
    testRunner.When("an unauthenticated user opens permalink for post \"Public onboarding post\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 167
    testRunner.Then("the post content should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 168
    testRunner.And("the public permalink should remain read-only for guests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 169
    testRunner.Given("Owner profile mode is Close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 170
    testRunner.And("Owner has created a Close post \"Guest gated post\" for Inner Circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 171
    testRunner.When("an unauthenticated user opens permalink for post \"Guest gated post\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 172
    testRunner.Then("the permalink denial contract should target guest account creation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="FollowSocialAuthor creates inner circle membership and direct chat for visible au" +
            "thor")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "FollowSocialAuthor creates inner circle membership and direct chat for visible au" +
            "thor")]
        [Xunit.TraitAttribute("Category", "FEAT-090")]
        [Xunit.TraitAttribute("Category", "HS-INT-090-FOLLOW")]
        public void FollowSocialAuthorCreatesInnerCircleMembershipAndDirectChatForVisibleAuthor()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-090",
                    "HS-INT-090-FOLLOW"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("FollowSocialAuthor creates inner circle membership and direct chat for visible au" +
                    "thor", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 175
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 176
    testRunner.Given("Owner has HushSocial enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 177
    testRunner.And("FollowerA has HushSocial enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 178
    testRunner.And("FollowerA does not have an Inner Circle yet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 179
    testRunner.When("FollowerA follows Owner via social follow contract", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 180
    testRunner.Then("the social follow response should be accepted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 181
    testRunner.And("Owner should be in FollowerA Inner Circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 182
    testRunner.And("FollowerA and Owner should have a direct chat feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Duplicate social follow rejection requires refresh without mutating follow state")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Duplicate social follow rejection requires refresh without mutating follow state")]
        [Xunit.TraitAttribute("Category", "FEAT-090")]
        [Xunit.TraitAttribute("Category", "HS-INT-090-FOLLOW")]
        public void DuplicateSocialFollowRejectionRequiresRefreshWithoutMutatingFollowState()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-090",
                    "HS-INT-090-FOLLOW"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Duplicate social follow rejection requires refresh without mutating follow state", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 185
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 186
    testRunner.Given("FollowerA already follows Owner via social follow contract", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 187
    testRunner.When("FollowerA follows Owner via social follow contract", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 188
    testRunner.Then("the social follow response should reject duplicate follow and require refresh", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 189
    testRunner.And("Owner should be in FollowerA Inner Circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Social follow contract rejects self follow")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Social follow contract rejects self follow")]
        [Xunit.TraitAttribute("Category", "FEAT-090")]
        [Xunit.TraitAttribute("Category", "HS-INT-090-FOLLOW")]
        public void SocialFollowContractRejectsSelfFollow()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-090",
                    "HS-INT-090-FOLLOW"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Social follow contract rejects self follow", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 192
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 193
    testRunner.When("Owner follows Owner via social follow contract", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 194
    testRunner.Then("the social follow response should reject self follow", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Notification delivery honors eligibility and privacy-safe payloads", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Notification delivery honors eligibility and privacy-safe payloads")]
        [Xunit.TraitAttribute("Category", "FEAT-091")]
        public void NotificationDeliveryHonorsEligibilityAndPrivacy_SafePayloads()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-091",
                    "ignore"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Notification delivery honors eligibility and privacy-safe payloads", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 197
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 198
    testRunner.Given("Owner profile mode is Close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 199
    testRunner.And("Owner has accepted follow request from FollowerA", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 200
    testRunner.And("Owner has not accepted follow request from FollowerC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 201
    testRunner.And("FollowerA has enabled Close post notifications", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 202
    testRunner.And("FollowerA has not muted circle \"Inner Circle\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 203
    testRunner.When("Owner publishes Close post \"Security update\" to Inner Circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 204
    testRunner.Then("FollowerA should receive in-app notification for \"Security update\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 205
    testRunner.And("FollowerA should receive push notification with no content preview", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 206
    testRunner.And("FollowerC should not receive any notification for \"Security update\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Per-circle mute suppresses notifications for muted circle", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "HushSocial server integration rules")]
        [Xunit.TraitAttribute("Description", "Per-circle mute suppresses notifications for muted circle")]
        [Xunit.TraitAttribute("Category", "FEAT-091")]
        public void Per_CircleMuteSuppressesNotificationsForMutedCircle()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-091",
                    "ignore"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Per-circle mute suppresses notifications for muted circle", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 209
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 210
    testRunner.Given("Owner profile mode is Close", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 211
    testRunner.And("Owner has accepted follow request from FollowerA", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 212
    testRunner.And("Owner has created circle \"Trading Circle\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 213
    testRunner.And("Owner has added FollowerA to circle \"Trading Circle\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 214
    testRunner.And("FollowerA has muted circle \"Trading Circle\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 215
    testRunner.When("Owner publishes Close post \"Trade signal\" to circle \"Trading Circle\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 216
    testRunner.Then("FollowerA should not receive in-app notification for \"Trade signal\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 217
    testRunner.And("FollowerA should not receive push notification for \"Trade signal\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                HushSocialServerIntegrationRulesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                HushSocialServerIntegrationRulesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
