// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HushNode.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "Integration")]
    [Xunit.TraitAttribute("Category", "EPIC-004")]
    [Xunit.TraitAttribute("Category", "FEAT-059")]
    public partial class FEAT_059Per_FeedPaginationAPIFeature : object, Xunit.IClassFixture<FEAT_059Per_FeedPaginationAPIFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "Integration",
                "EPIC-004",
                "FEAT-059"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PerFeedPagination.feature"
#line hidden
        
        public FEAT_059Per_FeedPaginationAPIFeature(FEAT_059Per_FeedPaginationAPIFeature.FixtureData fixtureData, HushNode_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "FEAT-059 Per-Feed Pagination API", "  As a client developer\r\n  I want to fetch messages for a specific feed with curs" +
                    "or pagination\r\n  So that I can implement scroll-based prefetch", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
  #line hidden
#line 8
    testRunner.Given("a HushServerNode at block 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
    testRunner.And("Redis cache is available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
    testRunner.And("user \"Alice\" is registered with a personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 11
    testRunner.And("user \"Bob\" is registered with a personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
    testRunner.And("Alice has a ChatFeed with Bob", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Per-feed pagination returns messages for specific feed")]
        [Xunit.TraitAttribute("FeatureTitle", "FEAT-059 Per-Feed Pagination API")]
        [Xunit.TraitAttribute("Description", "Per-feed pagination returns messages for specific feed")]
        [Xunit.TraitAttribute("Category", "PerFeedPagination")]
        public void Per_FeedPaginationReturnsMessagesForSpecificFeed()
        {
            string[] tagsOfScenario = new string[] {
                    "PerFeedPagination"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Per-feed pagination returns messages for specific feed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 18
    testRunner.Given("the ChatFeed contains 50 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 19
    testRunner.When("Alice calls GetFeedMessagesById for the ChatFeed via gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
    testRunner.Then("the per-feed response should contain exactly 50 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 21
    testRunner.And("the per-feed response has_more_messages should be false", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 22
    testRunner.And("all per-feed messages should belong to the ChatFeed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Per-feed pagination with cursor returns older messages")]
        [Xunit.TraitAttribute("FeatureTitle", "FEAT-059 Per-Feed Pagination API")]
        [Xunit.TraitAttribute("Description", "Per-feed pagination with cursor returns older messages")]
        [Xunit.TraitAttribute("Category", "PerFeedPagination")]
        public void Per_FeedPaginationWithCursorReturnsOlderMessages()
        {
            string[] tagsOfScenario = new string[] {
                    "PerFeedPagination"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Per-feed pagination with cursor returns older messages", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 26
    testRunner.Given("the ChatFeed contains 150 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 28
    testRunner.When("Alice calls GetFeedMessagesById for the ChatFeed via gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 29
    testRunner.Then("the per-feed response should contain exactly 100 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 30
    testRunner.And("the per-feed response has_more_messages should be true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
    testRunner.And("Alice records the per-feed oldest_block_index from the response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 33
    testRunner.When("Alice calls GetFeedMessagesById with beforeBlockIndex via gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
    testRunner.Then("the per-feed response should contain exactly 50 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
    testRunner.And("the per-feed response has_more_messages should be false", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Per-feed pagination with custom limit is respected")]
        [Xunit.TraitAttribute("FeatureTitle", "FEAT-059 Per-Feed Pagination API")]
        [Xunit.TraitAttribute("Description", "Per-feed pagination with custom limit is respected")]
        [Xunit.TraitAttribute("Category", "PerFeedPagination")]
        public void Per_FeedPaginationWithCustomLimitIsRespected()
        {
            string[] tagsOfScenario = new string[] {
                    "PerFeedPagination"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Per-feed pagination with custom limit is respected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 39
    testRunner.Given("the ChatFeed contains 50 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 40
    testRunner.When("Alice calls GetFeedMessagesById with limit 20 via gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 41
    testRunner.Then("the per-feed response should contain exactly 20 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 42
    testRunner.And("the per-feed response has_more_messages should be true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Three requests to paginate 250 messages in a specific feed")]
        [Xunit.TraitAttribute("FeatureTitle", "FEAT-059 Per-Feed Pagination API")]
        [Xunit.TraitAttribute("Description", "Three requests to paginate 250 messages in a specific feed")]
        [Xunit.TraitAttribute("Category", "PerFeedPagination")]
        [Xunit.TraitAttribute("Category", "MultiPage")]
        public void ThreeRequestsToPaginate250MessagesInASpecificFeed()
        {
            string[] tagsOfScenario = new string[] {
                    "PerFeedPagination",
                    "MultiPage"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Three requests to paginate 250 messages in a specific feed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 48
    testRunner.Given("the ChatFeed contains 250 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 50
    testRunner.When("Alice calls GetFeedMessagesById for the ChatFeed via gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 51
    testRunner.Then("the per-feed response should contain exactly 100 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 52
    testRunner.And("the per-feed response has_more_messages should be true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 53
    testRunner.And("Alice records the per-feed oldest_block_index from the response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 55
    testRunner.When("Alice calls GetFeedMessagesById with beforeBlockIndex via gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 56
    testRunner.Then("the per-feed response should contain exactly 100 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 57
    testRunner.And("the per-feed response has_more_messages should be true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 58
    testRunner.And("Alice records the per-feed oldest_block_index from the response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 60
    testRunner.When("Alice calls GetFeedMessagesById with beforeBlockIndex via gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 61
    testRunner.Then("the per-feed response should contain exactly 50 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 62
    testRunner.And("the per-feed response has_more_messages should be false", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Per-feed pagination denies access for non-participant")]
        [Xunit.TraitAttribute("FeatureTitle", "FEAT-059 Per-Feed Pagination API")]
        [Xunit.TraitAttribute("Description", "Per-feed pagination denies access for non-participant")]
        [Xunit.TraitAttribute("Category", "PerFeedPagination")]
        [Xunit.TraitAttribute("Category", "Authorization")]
        public void Per_FeedPaginationDeniesAccessForNon_Participant()
        {
            string[] tagsOfScenario = new string[] {
                    "PerFeedPagination",
                    "Authorization"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Per-feed pagination denies access for non-participant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 67
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 68
    testRunner.Given("the ChatFeed contains 20 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 69
    testRunner.And("user \"Charlie\" is registered with a personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 70
    testRunner.When("Charlie calls GetFeedMessagesById for the Alice-Bob ChatFeed via gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 71
    testRunner.Then("the per-feed response should contain exactly 0 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 72
    testRunner.And("the per-feed response has_more_messages should be false", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Per-feed pagination for empty feed returns no messages")]
        [Xunit.TraitAttribute("FeatureTitle", "FEAT-059 Per-Feed Pagination API")]
        [Xunit.TraitAttribute("Description", "Per-feed pagination for empty feed returns no messages")]
        [Xunit.TraitAttribute("Category", "PerFeedPagination")]
        [Xunit.TraitAttribute("Category", "EdgeCase")]
        public void Per_FeedPaginationForEmptyFeedReturnsNoMessages()
        {
            string[] tagsOfScenario = new string[] {
                    "PerFeedPagination",
                    "EdgeCase"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Per-feed pagination for empty feed returns no messages", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 77
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 78
    testRunner.When("Alice calls GetFeedMessagesById for the ChatFeed via gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 79
    testRunner.Then("the per-feed response should contain exactly 0 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 80
    testRunner.And("the per-feed response has_more_messages should be false", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Per-feed pagination with non-existent feed returns no messages")]
        [Xunit.TraitAttribute("FeatureTitle", "FEAT-059 Per-Feed Pagination API")]
        [Xunit.TraitAttribute("Description", "Per-feed pagination with non-existent feed returns no messages")]
        [Xunit.TraitAttribute("Category", "PerFeedPagination")]
        [Xunit.TraitAttribute("Category", "EdgeCase")]
        public void Per_FeedPaginationWithNon_ExistentFeedReturnsNoMessages()
        {
            string[] tagsOfScenario = new string[] {
                    "PerFeedPagination",
                    "EdgeCase"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Per-feed pagination with non-existent feed returns no messages", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 83
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 84
    testRunner.When("Alice calls GetFeedMessagesById for a non-existent feed via gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 85
    testRunner.Then("the per-feed response should contain exactly 0 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 86
    testRunner.And("the per-feed response has_more_messages should be false", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Per-feed pagination respects feed isolation")]
        [Xunit.TraitAttribute("FeatureTitle", "FEAT-059 Per-Feed Pagination API")]
        [Xunit.TraitAttribute("Description", "Per-feed pagination respects feed isolation")]
        [Xunit.TraitAttribute("Category", "PerFeedPagination")]
        [Xunit.TraitAttribute("Category", "EdgeCase")]
        public void Per_FeedPaginationRespectsFeedIsolation()
        {
            string[] tagsOfScenario = new string[] {
                    "PerFeedPagination",
                    "EdgeCase"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Per-feed pagination respects feed isolation", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 89
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 90
    testRunner.Given("the ChatFeed contains 30 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 91
    testRunner.And("a Charlie-Bob ChatFeed exists with 50 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 92
    testRunner.When("Alice calls GetFeedMessagesById for the ChatFeed via gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 93
    testRunner.Then("the per-feed response should contain exactly 30 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 94
    testRunner.And("all per-feed messages should belong to the ChatFeed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Per-feed pagination returns correct oldest and newest block indexes")]
        [Xunit.TraitAttribute("FeatureTitle", "FEAT-059 Per-Feed Pagination API")]
        [Xunit.TraitAttribute("Description", "Per-feed pagination returns correct oldest and newest block indexes")]
        [Xunit.TraitAttribute("Category", "PerFeedPagination")]
        [Xunit.TraitAttribute("Category", "ResponseFields")]
        public void Per_FeedPaginationReturnsCorrectOldestAndNewestBlockIndexes()
        {
            string[] tagsOfScenario = new string[] {
                    "PerFeedPagination",
                    "ResponseFields"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Per-feed pagination returns correct oldest and newest block indexes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 99
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 100
    testRunner.Given("the ChatFeed contains 50 messages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 101
    testRunner.When("Alice calls GetFeedMessagesById for the ChatFeed via gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 102
    testRunner.Then("the per-feed response oldest_block_index should be less than newest_block_index", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 103
    testRunner.And("the per-feed response newest_block_index should be the block of the newest messag" +
                        "e", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                FEAT_059Per_FeedPaginationAPIFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                FEAT_059Per_FeedPaginationAPIFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
