// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HushNode.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "Integration")]
    public partial class FEAT_049UserFeedsListCacheFeature : object, Xunit.IClassFixture<FEAT_049UserFeedsListCacheFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "Integration"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UserFeedsListCache.feature"
#line hidden
        
        public FEAT_049UserFeedsListCacheFeature(FEAT_049UserFeedsListCacheFeature.FixtureData fixtureData, HushNode_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "FEAT-049 User Feeds List Cache", "  As the sync endpoint\r\n  I want user feed lists cached\r\n  So that idle sync cycl" +
                    "es don\'t hit the database", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
  #line hidden
#line 8
    testRunner.Given("a HushServerNode at block 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
    testRunner.And("Redis cache is available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
    testRunner.And("user \"Alice\" is registered with a personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="User feed list is cached on first query")]
        [Xunit.TraitAttribute("FeatureTitle", "FEAT-049 User Feeds List Cache")]
        [Xunit.TraitAttribute("Description", "User feed list is cached on first query")]
        [Xunit.TraitAttribute("Category", "FEAT-049")]
        [Xunit.TraitAttribute("Category", "CacheAside")]
        public void UserFeedListIsCachedOnFirstQuery()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-049",
                    "CacheAside"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User feed list is cached on first query", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 15
    testRunner.Given("Alice\'s user feeds cache is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 16
    testRunner.When("Alice requests feed messages via GetFeedMessagesForAddress gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 17
    testRunner.Then("Alice\'s feed list should be in the Redis user feeds cache", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 18
    testRunner.And("the cache should contain Alice\'s personal feed ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="User feed list is returned from cache on subsequent queries")]
        [Xunit.TraitAttribute("FeatureTitle", "FEAT-049 User Feeds List Cache")]
        [Xunit.TraitAttribute("Description", "User feed list is returned from cache on subsequent queries")]
        [Xunit.TraitAttribute("Category", "FEAT-049")]
        [Xunit.TraitAttribute("Category", "CacheAside")]
        public void UserFeedListIsReturnedFromCacheOnSubsequentQueries()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-049",
                    "CacheAside"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User feed list is returned from cache on subsequent queries", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 22
    testRunner.Given("Alice\'s user feeds cache has been populated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 23
    testRunner.When("Alice requests feed messages via GetFeedMessagesForAddress gRPC again", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 24
    testRunner.Then("Alice\'s feed list should still be in the Redis user feeds cache", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="User feed list cache has 5-minute TTL")]
        [Xunit.TraitAttribute("FeatureTitle", "FEAT-049 User Feeds List Cache")]
        [Xunit.TraitAttribute("Description", "User feed list cache has 5-minute TTL")]
        [Xunit.TraitAttribute("Category", "FEAT-049")]
        [Xunit.TraitAttribute("Category", "TTL")]
        public void UserFeedListCacheHas5_MinuteTTL()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-049",
                    "TTL"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User feed list cache has 5-minute TTL", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 28
    testRunner.When("Alice requests feed messages via GetFeedMessagesForAddress gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 29
    testRunner.Then("the Redis user feeds cache TTL should be less than or equal to 5 minutes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Creating group feed adds to user\'s cached feed list")]
        [Xunit.TraitAttribute("FeatureTitle", "FEAT-049 User Feeds List Cache")]
        [Xunit.TraitAttribute("Description", "Creating group feed adds to user\'s cached feed list")]
        [Xunit.TraitAttribute("Category", "FEAT-049")]
        [Xunit.TraitAttribute("Category", "InPlaceUpdate")]
        public void CreatingGroupFeedAddsToUsersCachedFeedList()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-049",
                    "InPlaceUpdate"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Creating group feed adds to user\'s cached feed list", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 34
    testRunner.Given("Alice\'s user feeds cache has been populated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 35
    testRunner.And("Alice\'s user feeds cache count is recorded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 36
    testRunner.When("Alice creates a group feed \"TestGroup\" via gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 37
    testRunner.And("a block is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 38
    testRunner.Then("Alice\'s Redis user feeds cache should contain one more feed ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Creating chat feed updates both participants\' cached feed lists")]
        [Xunit.TraitAttribute("FeatureTitle", "FEAT-049 User Feeds List Cache")]
        [Xunit.TraitAttribute("Description", "Creating chat feed updates both participants\' cached feed lists")]
        [Xunit.TraitAttribute("Category", "FEAT-049")]
        [Xunit.TraitAttribute("Category", "InPlaceUpdate")]
        public void CreatingChatFeedUpdatesBothParticipantsCachedFeedLists()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-049",
                    "InPlaceUpdate"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Creating chat feed updates both participants\' cached feed lists", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 42
    testRunner.Given("user \"Bob\" is registered with a personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 43
    testRunner.And("Alice\'s user feeds cache has been populated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 44
    testRunner.And("Bob\'s user feeds cache has been populated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 45
    testRunner.And("Alice\'s user feeds cache count is recorded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 46
    testRunner.And("Bob\'s user feeds cache count is recorded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 47
    testRunner.When("Alice creates a ChatFeed with Bob via gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 48
    testRunner.And("a block is produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 49
    testRunner.Then("Alice\'s Redis user feeds cache should contain one more feed ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 50
    testRunner.And("Bob\'s Redis user feeds cache should contain one more feed ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Feed list query works after cache flush")]
        [Xunit.TraitAttribute("FeatureTitle", "FEAT-049 User Feeds List Cache")]
        [Xunit.TraitAttribute("Description", "Feed list query works after cache flush")]
        [Xunit.TraitAttribute("Category", "FEAT-049")]
        [Xunit.TraitAttribute("Category", "Fallback")]
        public void FeedListQueryWorksAfterCacheFlush()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-049",
                    "Fallback"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feed list query works after cache flush", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
#line 55
    testRunner.Given("Alice has feeds in the database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 56
    testRunner.And("the Redis cache is flushed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 57
    testRunner.When("Alice requests feed messages via GetFeedMessagesForAddress gRPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 58
    testRunner.Then("the response should succeed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 59
    testRunner.And("Alice\'s feed list should be in the Redis user feeds cache", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                FEAT_049UserFeedsListCacheFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                FEAT_049UserFeedsListCacheFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
