namespace HushNode.HushVoting.Licensing.Storage;

/// <summary>
/// Privacy-safe durable cache-delivery record written inside the same PostgreSQL transaction and
/// entitlement revision as a FEAT-013 state change (FEAT-014). Redis convergence is best-effort
/// immediately after commit and durable through dispatchers that claim these rows.
///
/// The row contains no signing address, no entitlement projection, and no cache payload: it only
/// identifies the internal subject, the committed revision to converge to, and delivery bookkeeping.
/// </summary>
public sealed class LicenceCacheOutboxEntity
{
    /// <summary>UUIDv7 identifier generated by the application at creation time.</summary>
    public Guid Id { get; set; }

    /// <summary>Internal FEAT-013 subject id; never the raw signing address.</summary>
    public Guid LicenceSubjectId { get; set; }

    /// <summary>Monotonic committed entitlement revision the cache must converge to.</summary>
    public long CommittedRevision { get; set; }

    /// <summary>Bounded change-kind vocabulary (<see cref="LicenceCacheOutboxChangeKinds"/>).</summary>
    public string ChangeKind { get; set; } = string.Empty;

    /// <summary>UTC creation instant (same transaction as the authoritative state change).</summary>
    public DateTime CreatedUtc { get; set; }

    /// <summary>UTC instant from which the row may next be claimed (backoff scheduling).</summary>
    public DateTime AvailableAfterUtc { get; set; }

    /// <summary>Monotonic attempt counter.</summary>
    public int AttemptCount { get; set; }

    /// <summary>Claim owner token while a dispatcher holds the row; null when claimable.</summary>
    public string? LeaseOwnerToken { get; set; }

    /// <summary>UTC instant when the current claim lease expires; null when claimable.</summary>
    public DateTime? LeaseExpiresUtc { get; set; }

    /// <summary>UTC delivery instant; null while pending.</summary>
    public DateTime? DeliveredUtc { get; set; }

    /// <summary>Bounded safe failure code of the latest failed attempt; null when none.</summary>
    public string? LastSafeErrorCode { get; set; }

    /// <summary>UTC instant of the latest delivery attempt.</summary>
    public DateTime? LastAttemptUtc { get; set; }

    /// <summary>Navigation to the owning subject (restrict delete; history preserved).</summary>
    public LicenceSubjectEntity? Subject { get; set; }
}
