<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <OutputPath>../../bin/$(Configuration)/node-process-host/</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../../HushServerNode/HushServerNode.csproj" />
  </ItemGroup>
</Project>
