// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HushNode.IntegrationTests.HushVoting.ServerTwins
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "HushVoting")]
    [Xunit.TraitAttribute("Category", "HV-SERVER-TWIN")]
    [Xunit.TraitAttribute("Category", "NON_E2E")]
    [Xunit.TraitAttribute("Category", "HV-ID-ENCODING-TWIN")]
    [Xunit.TraitAttribute("Category", "FEAT-011")]
    public partial class HushVotingExactIdentityEncodingsAndLookupBoundsFeature : object, Xunit.IClassFixture<HushVotingExactIdentityEncodingsAndLookupBoundsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "HushVoting",
                "HV-SERVER-TWIN",
                "NON_E2E",
                "HV-ID-ENCODING-TWIN",
                "FEAT-011"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "identity-encodings.feature"
#line hidden
        
        public HushVotingExactIdentityEncodingsAndLookupBoundsFeature(HushVotingExactIdentityEncodingsAndLookupBoundsFeature.FixtureData fixtureData, HushNode_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "HushVoting/ServerTwins", "HushVoting exact identity encodings and lookup bounds", "  FEAT-001 exact address contract; FEAT-011 Phase 3 Tasks 3.1/3.2 and 3.7/3.8.\n  " +
                    "Supporting FEAT-008/009 backend evidence, not EPIC browser acceptance.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="P01 compact admission preserves exact encoded identity")]
        [Xunit.TraitAttribute("FeatureTitle", "HushVoting exact identity encodings and lookup bounds")]
        [Xunit.TraitAttribute("Description", "P01 compact admission preserves exact encoded identity")]
        [Xunit.TraitAttribute("Category", "HV-TWIN-ID-ENCODING-001")]
        [Xunit.TraitAttribute("Category", "AC-008-076")]
        [Xunit.TraitAttribute("Category", "AC-009-081")]
        public void P01CompactAdmissionPreservesExactEncodedIdentity()
        {
            string[] tagsOfScenario = new string[] {
                    "HV-TWIN-ID-ENCODING-001",
                    "AC-008-076",
                    "AC-009-081"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("P01 compact admission preserves exact encoded identity", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
    testRunner.Given("an unregistered P01 identity uses an approved compact signature", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
    testRunner.When("the encoded identity is admitted and its exact bytes are retried before indexing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
    testRunner.Then("real indexing preserves the exact encoded pair and a duplicate adds no profile or" +
                        " transaction", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="P01 DER admission preserves exact encoded identity")]
        [Xunit.TraitAttribute("FeatureTitle", "HushVoting exact identity encodings and lookup bounds")]
        [Xunit.TraitAttribute("Description", "P01 DER admission preserves exact encoded identity")]
        [Xunit.TraitAttribute("Category", "HV-TWIN-ID-ENCODING-002")]
        [Xunit.TraitAttribute("Category", "AC-008-076")]
        [Xunit.TraitAttribute("Category", "AC-009-081")]
        public void P01DERAdmissionPreservesExactEncodedIdentity()
        {
            string[] tagsOfScenario = new string[] {
                    "HV-TWIN-ID-ENCODING-002",
                    "AC-008-076",
                    "AC-009-081"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("P01 DER admission preserves exact encoded identity", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 14
    testRunner.Given("an unregistered P01 identity uses an approved DER signature", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 15
    testRunner.When("the encoded identity is admitted and its exact bytes are retried before indexing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 16
    testRunner.Then("real indexing preserves the exact encoded pair and a duplicate adds no profile or" +
                        " transaction", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="P02 compact admission preserves exact encoded identity")]
        [Xunit.TraitAttribute("FeatureTitle", "HushVoting exact identity encodings and lookup bounds")]
        [Xunit.TraitAttribute("Description", "P02 compact admission preserves exact encoded identity")]
        [Xunit.TraitAttribute("Category", "HV-TWIN-ID-ENCODING-003")]
        [Xunit.TraitAttribute("Category", "AC-008-076")]
        [Xunit.TraitAttribute("Category", "AC-009-081")]
        public void P02CompactAdmissionPreservesExactEncodedIdentity()
        {
            string[] tagsOfScenario = new string[] {
                    "HV-TWIN-ID-ENCODING-003",
                    "AC-008-076",
                    "AC-009-081"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("P02 compact admission preserves exact encoded identity", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 20
    testRunner.Given("an unregistered P02 identity uses an approved compact signature", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 21
    testRunner.When("the encoded identity is admitted and its exact bytes are retried before indexing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 22
    testRunner.Then("real indexing preserves the exact encoded pair and a duplicate adds no profile or" +
                        " transaction", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="P02 DER admission preserves exact encoded identity")]
        [Xunit.TraitAttribute("FeatureTitle", "HushVoting exact identity encodings and lookup bounds")]
        [Xunit.TraitAttribute("Description", "P02 DER admission preserves exact encoded identity")]
        [Xunit.TraitAttribute("Category", "HV-TWIN-ID-ENCODING-004")]
        [Xunit.TraitAttribute("Category", "AC-008-076")]
        [Xunit.TraitAttribute("Category", "AC-009-081")]
        public void P02DERAdmissionPreservesExactEncodedIdentity()
        {
            string[] tagsOfScenario = new string[] {
                    "HV-TWIN-ID-ENCODING-004",
                    "AC-008-076",
                    "AC-009-081"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("P02 DER admission preserves exact encoded identity", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 26
    testRunner.Given("an unregistered P02 identity uses an approved DER signature", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 27
    testRunner.When("the encoded identity is admitted and its exact bytes are retried before indexing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 28
    testRunner.Then("real indexing preserves the exact encoded pair and a duplicate adds no profile or" +
                        " transaction", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Two encodings of the same curve points remain distinct exact profiles")]
        [Xunit.TraitAttribute("FeatureTitle", "HushVoting exact identity encodings and lookup bounds")]
        [Xunit.TraitAttribute("Description", "Two encodings of the same curve points remain distinct exact profiles")]
        [Xunit.TraitAttribute("Category", "HV-TWIN-ID-ENCODING-005")]
        [Xunit.TraitAttribute("Category", "AC-008-076")]
        [Xunit.TraitAttribute("Category", "AC-009-081")]
        public void TwoEncodingsOfTheSameCurvePointsRemainDistinctExactProfiles()
        {
            string[] tagsOfScenario = new string[] {
                    "HV-TWIN-ID-ENCODING-005",
                    "AC-008-076",
                    "AC-009-081"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Two encodings of the same curve points remain distinct exact profiles", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 32
    testRunner.Given("an unregistered P01 identity uses an approved compact signature", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 33
    testRunner.When("the encoded identity is admitted and its exact bytes are retried before indexing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
    testRunner.Then("the uncompressed encoding of the same P01 pair remains a separately registered ex" +
                        "act identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Invalid lookup bounds never produce authoritative absence")]
        [Xunit.TraitAttribute("FeatureTitle", "HushVoting exact identity encodings and lookup bounds")]
        [Xunit.TraitAttribute("Description", "Invalid lookup bounds never produce authoritative absence")]
        [Xunit.TraitAttribute("Category", "HV-TWIN-ID-ENCODING-006")]
        [Xunit.TraitAttribute("Category", "AC-008-076")]
        [Xunit.TraitAttribute("Category", "AC-009-081")]
        public void InvalidLookupBoundsNeverProduceAuthoritativeAbsence()
        {
            string[] tagsOfScenario = new string[] {
                    "HV-TWIN-ID-ENCODING-006",
                    "AC-008-076",
                    "AC-009-081"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invalid lookup bounds never produce authoritative absence", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 38
    testRunner.Given("an unregistered P01 identity uses an approved compact signature", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 39
    testRunner.When("invalid lookup bounds are rejected over RPC while a valid absent identity stays a" +
                        "bsent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 40
    testRunner.Then("real indexing preserves the exact encoded pair and a duplicate adds no profile or" +
                        " transaction", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                HushVotingExactIdentityEncodingsAndLookupBoundsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                HushVotingExactIdentityEncodingsAndLookupBoundsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
