// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HushNode.IntegrationTests.HushVoting.ServerTwins
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "HushVoting")]
    [Xunit.TraitAttribute("Category", "HV-SERVER-TWIN")]
    [Xunit.TraitAttribute("Category", "NON_E2E")]
    [Xunit.TraitAttribute("Category", "HV-ID-SHAPE-TWIN")]
    [Xunit.TraitAttribute("Category", "FEAT-011")]
    public partial class HushVotingMalformedTransactionRootAndPayload_KindBoundariesFeature : object, Xunit.IClassFixture<HushVotingMalformedTransactionRootAndPayload_KindBoundariesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "HushVoting",
                "HV-SERVER-TWIN",
                "NON_E2E",
                "HV-ID-SHAPE-TWIN",
                "FEAT-011"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "identity-ingress-shapes.feature"
#line hidden
        
        public HushVotingMalformedTransactionRootAndPayload_KindBoundariesFeature(HushVotingMalformedTransactionRootAndPayload_KindBoundariesFeature.FixtureData fixtureData, HushNode_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "HushVoting/ServerTwins", "HushVoting malformed transaction root and payload-kind boundaries", "  FEAT-011 Phase 3 Tasks 3.1/3.2 and 3.7/3.8.\n  Supports pending FEAT-007/008/009" +
                    " backend matrices, not EPIC acceptance.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Real ingress rejects missing-payload-kind as malformed transaction input")]
        [Xunit.TraitAttribute("FeatureTitle", "HushVoting malformed transaction root and payload-kind boundaries")]
        [Xunit.TraitAttribute("Description", "Real ingress rejects missing-payload-kind as malformed transaction input")]
        [Xunit.TraitAttribute("Category", "HV-TWIN-ID-SHAPE-001")]
        [Xunit.TraitAttribute("Category", "AC-007-071")]
        [Xunit.TraitAttribute("Category", "AC-008-076")]
        [Xunit.TraitAttribute("Category", "AC-009-081")]
        public void RealIngressRejectsMissing_Payload_KindAsMalformedTransactionInput()
        {
            string[] tagsOfScenario = new string[] {
                    "HV-TWIN-ID-SHAPE-001",
                    "AC-007-071",
                    "AC-008-076",
                    "AC-009-081"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Real ingress rejects missing-payload-kind as malformed transaction input", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
    testRunner.Given("the isolated real node has an unregistered P01 identity and a missing-payload-kin" +
                        "d request", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
    testRunner.When("the defective request reaches the unchanged SubmitSignedTransaction RPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
    testRunner.Then("ingress returns REJECTED with stable code MALFORMED_TRANSACTION_JSON and no mempo" +
                        "ol or indexed identity effect", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 11
    testRunner.And("the original valid identity is still accepted once and indexes with its exact pub" +
                        "lic pair", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Real ingress rejects numeric-payload-kind as malformed transaction input")]
        [Xunit.TraitAttribute("FeatureTitle", "HushVoting malformed transaction root and payload-kind boundaries")]
        [Xunit.TraitAttribute("Description", "Real ingress rejects numeric-payload-kind as malformed transaction input")]
        [Xunit.TraitAttribute("Category", "HV-TWIN-ID-SHAPE-002")]
        [Xunit.TraitAttribute("Category", "AC-007-071")]
        [Xunit.TraitAttribute("Category", "AC-008-076")]
        [Xunit.TraitAttribute("Category", "AC-009-081")]
        public void RealIngressRejectsNumeric_Payload_KindAsMalformedTransactionInput()
        {
            string[] tagsOfScenario = new string[] {
                    "HV-TWIN-ID-SHAPE-002",
                    "AC-007-071",
                    "AC-008-076",
                    "AC-009-081"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Real ingress rejects numeric-payload-kind as malformed transaction input", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 15
    testRunner.Given("the isolated real node has an unregistered P01 identity and a numeric-payload-kin" +
                        "d request", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 16
    testRunner.When("the defective request reaches the unchanged SubmitSignedTransaction RPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 17
    testRunner.Then("ingress returns REJECTED with stable code MALFORMED_TRANSACTION_JSON and no mempo" +
                        "ol or indexed identity effect", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 18
    testRunner.And("the original valid identity is still accepted once and indexes with its exact pub" +
                        "lic pair", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Real ingress rejects object-payload-kind as malformed transaction input")]
        [Xunit.TraitAttribute("FeatureTitle", "HushVoting malformed transaction root and payload-kind boundaries")]
        [Xunit.TraitAttribute("Description", "Real ingress rejects object-payload-kind as malformed transaction input")]
        [Xunit.TraitAttribute("Category", "HV-TWIN-ID-SHAPE-003")]
        [Xunit.TraitAttribute("Category", "AC-007-071")]
        [Xunit.TraitAttribute("Category", "AC-008-076")]
        [Xunit.TraitAttribute("Category", "AC-009-081")]
        public void RealIngressRejectsObject_Payload_KindAsMalformedTransactionInput()
        {
            string[] tagsOfScenario = new string[] {
                    "HV-TWIN-ID-SHAPE-003",
                    "AC-007-071",
                    "AC-008-076",
                    "AC-009-081"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Real ingress rejects object-payload-kind as malformed transaction input", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 22
    testRunner.Given("the isolated real node has an unregistered P01 identity and a object-payload-kind" +
                        " request", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 23
    testRunner.When("the defective request reaches the unchanged SubmitSignedTransaction RPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 24
    testRunner.Then("ingress returns REJECTED with stable code MALFORMED_TRANSACTION_JSON and no mempo" +
                        "ol or indexed identity effect", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 25
    testRunner.And("the original valid identity is still accepted once and indexes with its exact pub" +
                        "lic pair", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Real ingress rejects array-payload-kind as malformed transaction input")]
        [Xunit.TraitAttribute("FeatureTitle", "HushVoting malformed transaction root and payload-kind boundaries")]
        [Xunit.TraitAttribute("Description", "Real ingress rejects array-payload-kind as malformed transaction input")]
        [Xunit.TraitAttribute("Category", "HV-TWIN-ID-SHAPE-004")]
        [Xunit.TraitAttribute("Category", "AC-007-071")]
        [Xunit.TraitAttribute("Category", "AC-008-076")]
        [Xunit.TraitAttribute("Category", "AC-009-081")]
        public void RealIngressRejectsArray_Payload_KindAsMalformedTransactionInput()
        {
            string[] tagsOfScenario = new string[] {
                    "HV-TWIN-ID-SHAPE-004",
                    "AC-007-071",
                    "AC-008-076",
                    "AC-009-081"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Real ingress rejects array-payload-kind as malformed transaction input", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 29
    testRunner.Given("the isolated real node has an unregistered P01 identity and a array-payload-kind " +
                        "request", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 30
    testRunner.When("the defective request reaches the unchanged SubmitSignedTransaction RPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 31
    testRunner.Then("ingress returns REJECTED with stable code MALFORMED_TRANSACTION_JSON and no mempo" +
                        "ol or indexed identity effect", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 32
    testRunner.And("the original valid identity is still accepted once and indexes with its exact pub" +
                        "lic pair", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Real ingress rejects array-root as malformed transaction input")]
        [Xunit.TraitAttribute("FeatureTitle", "HushVoting malformed transaction root and payload-kind boundaries")]
        [Xunit.TraitAttribute("Description", "Real ingress rejects array-root as malformed transaction input")]
        [Xunit.TraitAttribute("Category", "HV-TWIN-ID-SHAPE-005")]
        [Xunit.TraitAttribute("Category", "AC-007-071")]
        [Xunit.TraitAttribute("Category", "AC-008-076")]
        [Xunit.TraitAttribute("Category", "AC-009-081")]
        public void RealIngressRejectsArray_RootAsMalformedTransactionInput()
        {
            string[] tagsOfScenario = new string[] {
                    "HV-TWIN-ID-SHAPE-005",
                    "AC-007-071",
                    "AC-008-076",
                    "AC-009-081"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Real ingress rejects array-root as malformed transaction input", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 36
    testRunner.Given("the isolated real node has an unregistered P01 identity and a array-root request", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 37
    testRunner.When("the defective request reaches the unchanged SubmitSignedTransaction RPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 38
    testRunner.Then("ingress returns REJECTED with stable code MALFORMED_TRANSACTION_JSON and no mempo" +
                        "ol or indexed identity effect", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 39
    testRunner.And("the original valid identity is still accepted once and indexes with its exact pub" +
                        "lic pair", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Real ingress rejects number-root as malformed transaction input")]
        [Xunit.TraitAttribute("FeatureTitle", "HushVoting malformed transaction root and payload-kind boundaries")]
        [Xunit.TraitAttribute("Description", "Real ingress rejects number-root as malformed transaction input")]
        [Xunit.TraitAttribute("Category", "HV-TWIN-ID-SHAPE-006")]
        [Xunit.TraitAttribute("Category", "AC-007-071")]
        [Xunit.TraitAttribute("Category", "AC-008-076")]
        [Xunit.TraitAttribute("Category", "AC-009-081")]
        public void RealIngressRejectsNumber_RootAsMalformedTransactionInput()
        {
            string[] tagsOfScenario = new string[] {
                    "HV-TWIN-ID-SHAPE-006",
                    "AC-007-071",
                    "AC-008-076",
                    "AC-009-081"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Real ingress rejects number-root as malformed transaction input", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 43
    testRunner.Given("the isolated real node has an unregistered P01 identity and a number-root request" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 44
    testRunner.When("the defective request reaches the unchanged SubmitSignedTransaction RPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 45
    testRunner.Then("ingress returns REJECTED with stable code MALFORMED_TRANSACTION_JSON and no mempo" +
                        "ol or indexed identity effect", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 46
    testRunner.And("the original valid identity is still accepted once and indexes with its exact pub" +
                        "lic pair", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Real ingress rejects string-root as malformed transaction input")]
        [Xunit.TraitAttribute("FeatureTitle", "HushVoting malformed transaction root and payload-kind boundaries")]
        [Xunit.TraitAttribute("Description", "Real ingress rejects string-root as malformed transaction input")]
        [Xunit.TraitAttribute("Category", "HV-TWIN-ID-SHAPE-007")]
        [Xunit.TraitAttribute("Category", "AC-007-071")]
        [Xunit.TraitAttribute("Category", "AC-008-076")]
        [Xunit.TraitAttribute("Category", "AC-009-081")]
        public void RealIngressRejectsString_RootAsMalformedTransactionInput()
        {
            string[] tagsOfScenario = new string[] {
                    "HV-TWIN-ID-SHAPE-007",
                    "AC-007-071",
                    "AC-008-076",
                    "AC-009-081"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Real ingress rejects string-root as malformed transaction input", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 49
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 50
    testRunner.Given("the isolated real node has an unregistered P01 identity and a string-root request" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 51
    testRunner.When("the defective request reaches the unchanged SubmitSignedTransaction RPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 52
    testRunner.Then("ingress returns REJECTED with stable code MALFORMED_TRANSACTION_JSON and no mempo" +
                        "ol or indexed identity effect", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 53
    testRunner.And("the original valid identity is still accepted once and indexes with its exact pub" +
                        "lic pair", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Real ingress rejects boolean-root as malformed transaction input")]
        [Xunit.TraitAttribute("FeatureTitle", "HushVoting malformed transaction root and payload-kind boundaries")]
        [Xunit.TraitAttribute("Description", "Real ingress rejects boolean-root as malformed transaction input")]
        [Xunit.TraitAttribute("Category", "HV-TWIN-ID-SHAPE-008")]
        [Xunit.TraitAttribute("Category", "AC-007-071")]
        [Xunit.TraitAttribute("Category", "AC-008-076")]
        [Xunit.TraitAttribute("Category", "AC-009-081")]
        public void RealIngressRejectsBoolean_RootAsMalformedTransactionInput()
        {
            string[] tagsOfScenario = new string[] {
                    "HV-TWIN-ID-SHAPE-008",
                    "AC-007-071",
                    "AC-008-076",
                    "AC-009-081"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Real ingress rejects boolean-root as malformed transaction input", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 57
    testRunner.Given("the isolated real node has an unregistered P01 identity and a boolean-root reques" +
                        "t", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 58
    testRunner.When("the defective request reaches the unchanged SubmitSignedTransaction RPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 59
    testRunner.Then("ingress returns REJECTED with stable code MALFORMED_TRANSACTION_JSON and no mempo" +
                        "ol or indexed identity effect", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 60
    testRunner.And("the original valid identity is still accepted once and indexes with its exact pub" +
                        "lic pair", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                HushVotingMalformedTransactionRootAndPayload_KindBoundariesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                HushVotingMalformedTransactionRootAndPayload_KindBoundariesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
