// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HushNode.IntegrationTests.HushVoting.Features.Credential_File_Restore
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "HushVoting")]
    [Xunit.TraitAttribute("Category", "HV-E2E")]
    [Xunit.TraitAttribute("Category", "E2E")]
    [Xunit.TraitAttribute("Category", "HV-CREDENTIAL-FILE-RESTORE")]
    [Xunit.TraitAttribute("Category", "HV-FEAT-009")]
    [Xunit.TraitAttribute("Category", "FEAT-009")]
    public partial class CredentialFileRestoreStrictSchemaKeyProofAndMnemonicFeature : object, Xunit.IClassFixture<CredentialFileRestoreStrictSchemaKeyProofAndMnemonicFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "HushVoting",
                "HV-E2E",
                "E2E",
                "HV-CREDENTIAL-FILE-RESTORE",
                "HV-FEAT-009",
                "FEAT-009"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "schema-keys-mnemonic.feature"
#line hidden
        
        public CredentialFileRestoreStrictSchemaKeyProofAndMnemonicFeature(CredentialFileRestoreStrictSchemaKeyProofAndMnemonicFeature.FixtureData fixtureData, HushNode_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "HushVoting/Features/credential-file-restore", "Credential file restore — Strict schema, key proof, and mnemonic", "  Covers HV-DAT-SCHEMA, HV-DAT-KEYS, HV-DAT-MNEMONIC.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AC-009-023 — HV-DAT-SCHEMA")]
        [Xunit.TraitAttribute("FeatureTitle", "Credential file restore — Strict schema, key proof, and mnemonic")]
        [Xunit.TraitAttribute("Description", "AC-009-023 — HV-DAT-SCHEMA")]
        [Xunit.TraitAttribute("Category", "FEAT-009")]
        [Xunit.TraitAttribute("Category", "AC-009-023")]
        [Xunit.TraitAttribute("Category", "HV-DAT-SCHEMA-AC023")]
        [Xunit.TraitAttribute("Category", "HV-DAT-VALIDATION-MIGRATED")]
        public void AC_009_023HV_DAT_SCHEMA()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-009",
                    "AC-009-023",
                    "HV-DAT-SCHEMA-AC023",
                    "HV-DAT-VALIDATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AC-009-023 — HV-DAT-SCHEMA", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
    testRunner.Given("independently authenticated credential payloads are ready for the real browser wo" +
                        "rker", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
    testRunner.When("Alice imports authenticated JSON with duplicate, unknown, missing, invalid-type, " +
                        "and out-of-bounds fields", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
    testRunner.Then("invalid credential data is rejected before lookup and a consistent backup reaches" +
                        " the live node", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AC-009-024 — HV-DAT-KEYS")]
        [Xunit.TraitAttribute("FeatureTitle", "Credential file restore — Strict schema, key proof, and mnemonic")]
        [Xunit.TraitAttribute("Description", "AC-009-024 — HV-DAT-KEYS")]
        [Xunit.TraitAttribute("Category", "FEAT-009")]
        [Xunit.TraitAttribute("Category", "AC-009-024")]
        [Xunit.TraitAttribute("Category", "HV-DAT-KEYS-AC024")]
        [Xunit.TraitAttribute("Category", "HV-DAT-VALIDATION-MIGRATED")]
        public void AC_009_024HV_DAT_KEYS()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-009",
                    "AC-009-024",
                    "HV-DAT-KEYS-AC024",
                    "HV-DAT-VALIDATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AC-009-024 — HV-DAT-KEYS", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 14
    testRunner.Given("independently authenticated credential payloads are ready for the real browser wo" +
                        "rker", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 15
    testRunner.When("Alice imports a backup whose signing private key disagrees with its public addres" +
                        "s", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 16
    testRunner.Then("invalid credential data is rejected before lookup and a consistent backup reaches" +
                        " the live node", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AC-009-025 — HV-DAT-KEYS")]
        [Xunit.TraitAttribute("FeatureTitle", "Credential file restore — Strict schema, key proof, and mnemonic")]
        [Xunit.TraitAttribute("Description", "AC-009-025 — HV-DAT-KEYS")]
        [Xunit.TraitAttribute("Category", "FEAT-009")]
        [Xunit.TraitAttribute("Category", "AC-009-025")]
        [Xunit.TraitAttribute("Category", "HV-DAT-KEYS-AC025")]
        [Xunit.TraitAttribute("Category", "HV-DAT-VALIDATION-MIGRATED")]
        public void AC_009_025HV_DAT_KEYS()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-009",
                    "AC-009-025",
                    "HV-DAT-KEYS-AC025",
                    "HV-DAT-VALIDATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AC-009-025 — HV-DAT-KEYS", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 20
    testRunner.Given("independently authenticated credential payloads are ready for the real browser wo" +
                        "rker", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 21
    testRunner.When("Alice imports a backup whose encryption private key disagrees with its public add" +
                        "ress", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 22
    testRunner.Then("invalid credential data is rejected before lookup and a consistent backup reaches" +
                        " the live node", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AC-009-026 — HV-DAT-KEYS")]
        [Xunit.TraitAttribute("FeatureTitle", "Credential file restore — Strict schema, key proof, and mnemonic")]
        [Xunit.TraitAttribute("Description", "AC-009-026 — HV-DAT-KEYS")]
        [Xunit.TraitAttribute("Category", "FEAT-009")]
        [Xunit.TraitAttribute("Category", "AC-009-026")]
        [Xunit.TraitAttribute("Category", "HV-DAT-KEYS-AC026")]
        public void AC_009_026HV_DAT_KEYS()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-009",
                    "AC-009-026",
                    "HV-DAT-KEYS-AC026"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AC-009-026 — HV-DAT-KEYS", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 26
    testRunner.Given("concrete signing and encryption pairs are present", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 27
    testRunner.When("local key-control proof runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 28
    testRunner.Then("both private keys independently derive exact stored public addresses and pass dom" +
                        "ain-separated consistency checks before lookup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AC-009-027 — HV-DAT-MNEMONIC")]
        [Xunit.TraitAttribute("FeatureTitle", "Credential file restore — Strict schema, key proof, and mnemonic")]
        [Xunit.TraitAttribute("Description", "AC-009-027 — HV-DAT-MNEMONIC")]
        [Xunit.TraitAttribute("Category", "FEAT-009")]
        [Xunit.TraitAttribute("Category", "AC-009-027")]
        [Xunit.TraitAttribute("Category", "HV-DAT-MNEMONIC-AC027")]
        [Xunit.TraitAttribute("Category", "HV-DAT-VALIDATION-MIGRATED")]
        public void AC_009_027HV_DAT_MNEMONIC()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-009",
                    "AC-009-027",
                    "HV-DAT-MNEMONIC-AC027",
                    "HV-DAT-VALIDATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AC-009-027 — HV-DAT-MNEMONIC", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 32
    testRunner.Given("independently authenticated credential payloads are ready for the real browser wo" +
                        "rker", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 33
    testRunner.When("Alice imports a backup with a valid phrase that derives different concrete keys", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
    testRunner.Then("invalid credential data is rejected before lookup and a consistent backup reaches" +
                        " the live node", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AC-009-028 — HV-DAT-MNEMONIC")]
        [Xunit.TraitAttribute("FeatureTitle", "Credential file restore — Strict schema, key proof, and mnemonic")]
        [Xunit.TraitAttribute("Description", "AC-009-028 — HV-DAT-MNEMONIC")]
        [Xunit.TraitAttribute("Category", "FEAT-009")]
        [Xunit.TraitAttribute("Category", "AC-009-028")]
        [Xunit.TraitAttribute("Category", "HV-DAT-MNEMONIC-AC028")]
        [Xunit.TraitAttribute("Category", "HV-DAT-VALIDATION-MIGRATED")]
        public void AC_009_028HV_DAT_MNEMONIC()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-009",
                    "AC-009-028",
                    "HV-DAT-MNEMONIC-AC028",
                    "HV-DAT-VALIDATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AC-009-028 — HV-DAT-MNEMONIC", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 38
    testRunner.Given("independently authenticated credential payloads are ready for the real browser wo" +
                        "rker", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 39
    testRunner.When("Alice decrypts a valid internally consistent backup with a null mnemonic", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 40
    testRunner.Then("the decrypted candidate still requires explicit profile confirmation and separate" +
                        " protection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AC-009-029 — HV-DAT-KEYS")]
        [Xunit.TraitAttribute("FeatureTitle", "Credential file restore — Strict schema, key proof, and mnemonic")]
        [Xunit.TraitAttribute("Description", "AC-009-029 — HV-DAT-KEYS")]
        [Xunit.TraitAttribute("Category", "FEAT-009")]
        [Xunit.TraitAttribute("Category", "AC-009-029")]
        [Xunit.TraitAttribute("Category", "HV-DAT-KEYS-AC029")]
        [Xunit.TraitAttribute("Category", "HV-DAT-VALIDATION-MIGRATED")]
        public void AC_009_029HV_DAT_KEYS()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-009",
                    "AC-009-029",
                    "HV-DAT-KEYS-AC029",
                    "HV-DAT-VALIDATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AC-009-029 — HV-DAT-KEYS", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 44
    testRunner.Given("independently authenticated credential payloads are ready for the real browser wo" +
                        "rker", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 45
    testRunner.When("Alice imports backups with malformed or unsupported key encodings", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 46
    testRunner.Then("invalid credential data is rejected before lookup and a consistent backup reaches" +
                        " the live node", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AC-009-030 — HV-DAT-KEYS")]
        [Xunit.TraitAttribute("FeatureTitle", "Credential file restore — Strict schema, key proof, and mnemonic")]
        [Xunit.TraitAttribute("Description", "AC-009-030 — HV-DAT-KEYS")]
        [Xunit.TraitAttribute("Category", "FEAT-009")]
        [Xunit.TraitAttribute("Category", "AC-009-030")]
        [Xunit.TraitAttribute("Category", "HV-DAT-KEYS-AC030")]
        [Xunit.TraitAttribute("Category", "HV-DAT-VALIDATION-MIGRATED")]
        public void AC_009_030HV_DAT_KEYS()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-009",
                    "AC-009-030",
                    "HV-DAT-KEYS-AC030",
                    "HV-DAT-VALIDATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AC-009-030 — HV-DAT-KEYS", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 49
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 50
    testRunner.Given("independently authenticated credential payloads are ready for the real browser wo" +
                        "rker", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 51
    testRunner.When("Alice imports schema, key-pair, and mnemonic inconsistencies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 52
    testRunner.Then("the visible inconsistency message is shared while safe internal failure codes rem" +
                        "ain distinct", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AC-009-031 — HV-DAT-SCHEMA")]
        [Xunit.TraitAttribute("FeatureTitle", "Credential file restore — Strict schema, key proof, and mnemonic")]
        [Xunit.TraitAttribute("Description", "AC-009-031 — HV-DAT-SCHEMA")]
        [Xunit.TraitAttribute("Category", "FEAT-009")]
        [Xunit.TraitAttribute("Category", "AC-009-031")]
        [Xunit.TraitAttribute("Category", "HV-DAT-SCHEMA-AC031")]
        [Xunit.TraitAttribute("Category", "HV-DAT-VALIDATION-MIGRATED")]
        public void AC_009_031HV_DAT_SCHEMA()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-009",
                    "AC-009-031",
                    "HV-DAT-SCHEMA-AC031",
                    "HV-DAT-VALIDATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AC-009-031 — HV-DAT-SCHEMA", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 56
    testRunner.Given("independently authenticated credential payloads are ready for the real browser wo" +
                        "rker", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 57
    testRunner.When("Alice imports schema, key-pair, and mnemonic inconsistencies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 58
    testRunner.Then("the visible inconsistency message is shared while safe internal failure codes rem" +
                        "ain distinct", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 59
    testRunner.And("semantic failures expose no decrypted values and a fresh valid import uses only i" +
                        "ts own identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AC-009-032 — HV-DAT-KEYS")]
        [Xunit.TraitAttribute("FeatureTitle", "Credential file restore — Strict schema, key proof, and mnemonic")]
        [Xunit.TraitAttribute("Description", "AC-009-032 — HV-DAT-KEYS")]
        [Xunit.TraitAttribute("Category", "FEAT-009")]
        [Xunit.TraitAttribute("Category", "AC-009-032")]
        [Xunit.TraitAttribute("Category", "HV-DAT-KEYS-AC032")]
        [Xunit.TraitAttribute("Category", "HV-DAT-VALIDATION-MIGRATED")]
        public void AC_009_032HV_DAT_KEYS()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-009",
                    "AC-009-032",
                    "HV-DAT-KEYS-AC032",
                    "HV-DAT-VALIDATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AC-009-032 — HV-DAT-KEYS", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 62
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 63
    testRunner.Given("independently authenticated credential payloads are ready for the real browser wo" +
                        "rker", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 64
    testRunner.When("Alice decrypts a valid internally consistent backup with a null mnemonic", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 65
    testRunner.Then("the decrypted candidate still requires explicit profile confirmation and separate" +
                        " protection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AC-009-033 — HV-DAT-MNEMONIC")]
        [Xunit.TraitAttribute("FeatureTitle", "Credential file restore — Strict schema, key proof, and mnemonic")]
        [Xunit.TraitAttribute("Description", "AC-009-033 — HV-DAT-MNEMONIC")]
        [Xunit.TraitAttribute("Category", "FEAT-009")]
        [Xunit.TraitAttribute("Category", "AC-009-033")]
        [Xunit.TraitAttribute("Category", "HV-DAT-MNEMONIC-AC033")]
        [Xunit.TraitAttribute("Category", "HV-DAT-VALIDATION-MIGRATED")]
        public void AC_009_033HV_DAT_MNEMONIC()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-009",
                    "AC-009-033",
                    "HV-DAT-MNEMONIC-AC033",
                    "HV-DAT-VALIDATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AC-009-033 — HV-DAT-MNEMONIC", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 68
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 69
    testRunner.Given("Alice has an independently encrypted registered backup containing its matching le" +
                        "gacy recovery words", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 70
    testRunner.When("Alice decrypts the backup with its exact untrimmed UTF-8 password", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 71
    testRunner.Then("the browser decrypts the approved PBKDF2 and AES-GCM envelope without altering it" +
                        "s keys", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 72
    testRunner.And("separate device protection restores that identity through the live node", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 73
    testRunner.And("independent inspection and a fresh unlock find only the imported concrete keys an" +
                        "d no recovery reveal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AC-009-034 — HV-DAT-MNEMONIC")]
        [Xunit.TraitAttribute("FeatureTitle", "Credential file restore — Strict schema, key proof, and mnemonic")]
        [Xunit.TraitAttribute("Description", "AC-009-034 — HV-DAT-MNEMONIC")]
        [Xunit.TraitAttribute("Category", "FEAT-009")]
        [Xunit.TraitAttribute("Category", "AC-009-034")]
        [Xunit.TraitAttribute("Category", "HV-DAT-MNEMONIC-AC034")]
        [Xunit.TraitAttribute("Category", "HV-DAT-VALIDATION-MIGRATED")]
        public void AC_009_034HV_DAT_MNEMONIC()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-009",
                    "AC-009-034",
                    "HV-DAT-MNEMONIC-AC034",
                    "HV-DAT-VALIDATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AC-009-034 — HV-DAT-MNEMONIC", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 76
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 77
    testRunner.Given("Alice selects a real unchanged source file containing her encrypted registered ke" +
                        "ys and recovery words", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 78
    testRunner.When("Alice decrypts the backup with its exact untrimmed UTF-8 password", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 79
    testRunner.Then("the browser decrypts the approved PBKDF2 and AES-GCM envelope without altering it" +
                        "s keys", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 80
    testRunner.And("separate device protection restores that identity through the live node", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 81
    testRunner.And("the original file remains byte for byte unchanged and the verified root explains " +
                        "recovery words were not retained", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CredentialFileRestoreStrictSchemaKeyProofAndMnemonicFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CredentialFileRestoreStrictSchemaKeyProofAndMnemonicFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
