namespace HushShared.Elections.Model;

public static partial class ElectionModelFactory
{
    public static ElectionTrusteeContinuityDecisionRecord CreateKeyLostTrusteeContinuityDecision(
        ElectionId electionId,
        string trusteePublicAddress,
        string? trusteeDisplayName,
        string authorityDecisionRef,
        string authorityDecisionHash,
        string governanceRuleRef,
        IReadOnlyList<string> continuityEvidenceRefs,
        string recordedByPublicAddress,
        DateTime? decidedAtUtc = null,
        DateTime? recordedAtUtc = null,
        Guid? sourceTransactionId = null,
        long? sourceBlockHeight = null,
        Guid? sourceBlockId = null,
        Guid? preassignedDecisionId = null) =>
        new(
            preassignedDecisionId ?? Guid.NewGuid(),
            electionId,
            NormalizeRequiredText(trusteePublicAddress, nameof(trusteePublicAddress)),
            NormalizeOptionalText(trusteeDisplayName),
            ElectionTrusteeContinuityStatus.KeyLost,
            NormalizeRequiredText(authorityDecisionRef, nameof(authorityDecisionRef)),
            NormalizeRequiredText(authorityDecisionHash, nameof(authorityDecisionHash)),
            NormalizeRequiredText(governanceRuleRef, nameof(governanceRuleRef)),
            continuityEvidenceRefs,
            NormalizeRequiredText(recordedByPublicAddress, nameof(recordedByPublicAddress)),
            decidedAtUtc ?? DateTime.UtcNow,
            recordedAtUtc ?? DateTime.UtcNow,
            sourceTransactionId,
            sourceBlockHeight,
            sourceBlockId);

    public static ElectionGovernedOutcomeDecisionRecord CreateFixedUnofficialResultAcceptedWithAnomalyDecision(
        ElectionRecord election,
        string actorPublicAddress,
        string authorityRole,
        string authoritySource,
        string feat140HandoffRef,
        string feat140HandoffHash,
        string authorityDecisionRef,
        string authorityDecisionHash,
        string governanceRuleRef,
        Guid closeArtifactId,
        Guid tallyReadyArtifactId,
        Guid unofficialResultArtifactId,
        Guid officialResultArtifactId,
        Guid officialResultSourceArtifactId,
        string publicSummary,
        IReadOnlyList<string>? missingFinalizeEvidenceRefs = null,
        IReadOnlyList<string>? continuityIncidentEvidenceRefs = null,
        IReadOnlyList<string>? availableTrusteeAcknowledgementRefs = null,
        IReadOnlyList<Guid>? keyLostTrusteeDecisionIds = null,
        Guid? finalizeArtifactId = null,
        string? finalityRuleRef = null,
        string? remedyRuleRef = null,
        DateTime? decidedAtUtc = null,
        DateTime? recordedAtUtc = null,
        Guid? sourceTransactionId = null,
        long? sourceBlockHeight = null,
        Guid? sourceBlockId = null,
        Guid? preassignedDecisionId = null)
    {
        ArgumentNullException.ThrowIfNull(election);

        return new ElectionGovernedOutcomeDecisionRecord(
            preassignedDecisionId ?? Guid.NewGuid(),
            election.ElectionId,
            ElectionGovernedOutcomeDecisionType.AcceptFixedUnofficialResultWithAnomaly,
            ElectionOutcomeStatus.FinalizedWithAnomaly,
            CleanFinalization: false,
            ElectionGovernedOutcomeFinalizationMode.AbnormalFinalization,
            election.LifecycleState,
            ElectionLifecycleState.Finalized,
            NormalizeRequiredText(actorPublicAddress, nameof(actorPublicAddress)),
            NormalizeRequiredText(authorityRole, nameof(authorityRole)),
            NormalizeRequiredText(authoritySource, nameof(authoritySource)),
            NormalizeRequiredText(feat140HandoffRef, nameof(feat140HandoffRef)),
            NormalizeRequiredText(feat140HandoffHash, nameof(feat140HandoffHash)),
            NormalizeRequiredText(authorityDecisionRef, nameof(authorityDecisionRef)),
            NormalizeRequiredText(authorityDecisionHash, nameof(authorityDecisionHash)),
            NormalizeRequiredText(governanceRuleRef, nameof(governanceRuleRef)),
            NormalizeOptionalText(finalityRuleRef),
            NormalizeOptionalText(remedyRuleRef),
            closeArtifactId,
            tallyReadyArtifactId,
            unofficialResultArtifactId,
            officialResultArtifactId,
            officialResultSourceArtifactId,
            finalizeArtifactId,
            missingFinalizeEvidenceRefs ?? Array.Empty<string>(),
            continuityIncidentEvidenceRefs ?? Array.Empty<string>(),
            availableTrusteeAcknowledgementRefs ?? Array.Empty<string>(),
            keyLostTrusteeDecisionIds ?? Array.Empty<Guid>(),
            NormalizeRequiredText(publicSummary, nameof(publicSummary)),
            decidedAtUtc ?? DateTime.UtcNow,
            recordedAtUtc ?? DateTime.UtcNow,
            sourceTransactionId,
            sourceBlockHeight,
            sourceBlockId);
    }
}
