// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HushNode.IntegrationTests.Features.E2E
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "E2E")]
    [Xunit.TraitAttribute("Category", "EPIC-004")]
    [Xunit.TraitAttribute("Category", "FEAT-059")]
    public partial class Auto_PaginationScroll_BasedPrefetchFeature : object, Xunit.IClassFixture<Auto_PaginationScroll_BasedPrefetchFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "E2E",
                "EPIC-004",
                "FEAT-059"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AutoPagination.feature"
#line hidden
        
        public Auto_PaginationScroll_BasedPrefetchFeature(Auto_PaginationScroll_BasedPrefetchFeature.FixtureData fixtureData, HushNode_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/E2E", "Auto-Pagination Scroll-Based Prefetch", "    As a user of Hush Feeds\r\n    I want messages to prefetch as I scroll through " +
                    "history\r\n    So that I have a seamless scrolling experience", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
    #line hidden
#line 8
        testRunner.Given("a HushServerNode at block 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
        testRunner.And("HushWebClient is running in Docker", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
        testRunner.And("a browser is launched", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Feed open initializes prefetch state")]
        [Xunit.TraitAttribute("FeatureTitle", "Auto-Pagination Scroll-Based Prefetch")]
        [Xunit.TraitAttribute("Description", "Feed open initializes prefetch state")]
        [Xunit.TraitAttribute("Category", "InitialLoad")]
        [Xunit.TraitAttribute("Category", "Automatable")]
        public void FeedOpenInitializesPrefetchState()
        {
            string[] tagsOfScenario = new string[] {
                    "InitialLoad",
                    "Automatable"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feed open initializes prefetch state", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 16
        testRunner.Given("the user has created identity \"Alice\" via browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 17
        testRunner.And("the user clicks on their personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 21
        testRunner.Then("the prefetch state should be initialized for the current feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Jump to bottom button appears when scrolled up and clicking scrolls to bottom")]
        [Xunit.TraitAttribute("FeatureTitle", "Auto-Pagination Scroll-Based Prefetch")]
        [Xunit.TraitAttribute("Description", "Jump to bottom button appears when scrolled up and clicking scrolls to bottom")]
        [Xunit.TraitAttribute("Category", "JumpToBottom")]
        [Xunit.TraitAttribute("Category", "Automatable")]
        public void JumpToBottomButtonAppearsWhenScrolledUpAndClickingScrollsToBottom()
        {
            string[] tagsOfScenario = new string[] {
                    "JumpToBottom",
                    "Automatable"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Jump to bottom button appears when scrolled up and clicking scrolls to bottom", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 28
        testRunner.Given("the user has created identity \"Alice\" via browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 29
        testRunner.And("the user clicks on their personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 30
        testRunner.And("Alice has sent 15 messages to their personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
        testRunner.And("the transactions are processed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 34
        testRunner.Then("the chat view should be at the bottom", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
        testRunner.And("the jump to bottom button should not be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 38
        testRunner.When("Alice scrolls up in the message list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 39
        testRunner.Then("the jump to bottom button should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 42
        testRunner.When("Alice clicks the jump to bottom button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 43
        testRunner.Then("the chat view should be at the bottom", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 44
        testRunner.And("the jump to bottom button should not be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Returning to feed starts fresh with newest messages")]
        [Xunit.TraitAttribute("FeatureTitle", "Auto-Pagination Scroll-Based Prefetch")]
        [Xunit.TraitAttribute("Description", "Returning to feed starts fresh with newest messages")]
        [Xunit.TraitAttribute("Category", "FreshStart")]
        [Xunit.TraitAttribute("Category", "Automatable")]
        public void ReturningToFeedStartsFreshWithNewestMessages()
        {
            string[] tagsOfScenario = new string[] {
                    "FreshStart",
                    "Automatable"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Returning to feed starts fresh with newest messages", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 50
        testRunner.Given("the user has created identity \"Alice\" via browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 51
        testRunner.And("the user clicks on their personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 52
        testRunner.And("Alice has sent 3 messages to their personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 53
        testRunner.And("the transactions are processed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 56
        testRunner.When("Alice clicks on the \"new-chat\" navigation item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 57
        testRunner.And("Alice waits for cleanup debounce (200ms)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 58
        testRunner.And("Alice clicks on the \"feeds\" navigation item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 59
        testRunner.And("Alice clicks on their personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 62
        testRunner.Then("the most recent message should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 63
        testRunner.And("the chat view should be at the bottom", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Prefetch triggered at 25% threshold")]
        [Xunit.TraitAttribute("FeatureTitle", "Auto-Pagination Scroll-Based Prefetch")]
        [Xunit.TraitAttribute("Description", "Prefetch triggered at 25% threshold")]
        [Xunit.TraitAttribute("Category", "ScrollPrefetch")]
        [Xunit.TraitAttribute("Category", "Manual")]
        public void PrefetchTriggeredAt25Threshold()
        {
            string[] tagsOfScenario = new string[] {
                    "ScrollPrefetch",
                    "Manual"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Prefetch triggered at 25% threshold", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 77
        testRunner.Given("this scenario requires manual testing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 78
        testRunner.Then("skip automated verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Loading spinner shows when scrolling faster than prefetch")]
        [Xunit.TraitAttribute("FeatureTitle", "Auto-Pagination Scroll-Based Prefetch")]
        [Xunit.TraitAttribute("Description", "Loading spinner shows when scrolling faster than prefetch")]
        [Xunit.TraitAttribute("Category", "SpinnerDisplay")]
        [Xunit.TraitAttribute("Category", "Manual")]
        public void LoadingSpinnerShowsWhenScrollingFasterThanPrefetch()
        {
            string[] tagsOfScenario = new string[] {
                    "SpinnerDisplay",
                    "Manual"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Loading spinner shows when scrolling faster than prefetch", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 81
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 88
        testRunner.Given("this scenario requires manual testing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 89
        testRunner.Then("skip automated verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Multiple feeds load in parallel after sync")]
        [Xunit.TraitAttribute("FeatureTitle", "Auto-Pagination Scroll-Based Prefetch")]
        [Xunit.TraitAttribute("Description", "Multiple feeds load in parallel after sync")]
        [Xunit.TraitAttribute("Category", "ParallelPrefetch")]
        [Xunit.TraitAttribute("Category", "Manual")]
        public void MultipleFeedsLoadInParallelAfterSync()
        {
            string[] tagsOfScenario = new string[] {
                    "ParallelPrefetch",
                    "Manual"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Multiple feeds load in parallel after sync", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 92
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 98
        testRunner.Given("this scenario requires manual testing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 99
        testRunner.Then("skip automated verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Prefetch failure retries silently")]
        [Xunit.TraitAttribute("FeatureTitle", "Auto-Pagination Scroll-Based Prefetch")]
        [Xunit.TraitAttribute("Description", "Prefetch failure retries silently")]
        [Xunit.TraitAttribute("Category", "SilentRetry")]
        [Xunit.TraitAttribute("Category", "Manual")]
        public void PrefetchFailureRetriesSilently()
        {
            string[] tagsOfScenario = new string[] {
                    "SilentRetry",
                    "Manual"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Prefetch failure retries silently", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 102
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 110
        testRunner.Given("this scenario requires manual testing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 111
        testRunner.Then("skip automated verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="All loaded pages remain in memory while viewing feed")]
        [Xunit.TraitAttribute("FeatureTitle", "Auto-Pagination Scroll-Based Prefetch")]
        [Xunit.TraitAttribute("Description", "All loaded pages remain in memory while viewing feed")]
        [Xunit.TraitAttribute("Category", "KeepInMemory")]
        [Xunit.TraitAttribute("Category", "Manual")]
        public void AllLoadedPagesRemainInMemoryWhileViewingFeed()
        {
            string[] tagsOfScenario = new string[] {
                    "KeepInMemory",
                    "Manual"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All loaded pages remain in memory while viewing feed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 115
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 127
        testRunner.Given("this scenario requires manual testing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 128
        testRunner.Then("skip automated verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                Auto_PaginationScroll_BasedPrefetchFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                Auto_PaginationScroll_BasedPrefetchFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
