// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HushNode.IntegrationTests.Features.E2E
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "E2E")]
    [Xunit.TraitAttribute("Category", "EPIC-003")]
    [Xunit.TraitAttribute("Category", "FEAT-055")]
    public partial class House_CleaningOnFeedCloseFeature : object, Xunit.IClassFixture<House_CleaningOnFeedCloseFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "E2E",
                "EPIC-003",
                "FEAT-055"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "HouseCleaning.feature"
#line hidden
        
        public House_CleaningOnFeedCloseFeature(House_CleaningOnFeedCloseFeature.FixtureData fixtureData, HushNode_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/E2E", "House-cleaning on Feed Close", "    As a user navigating between feeds\r\n    I want the previous feed\'s data to be" +
                    " cleaned up automatically\r\n    So that the app remains performant and memory usa" +
                    "ge stays controlled", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
    #line hidden
#line 8
        testRunner.Given("a HushServerNode at block 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
        testRunner.And("HushWebClient is running in Docker", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
        testRunner.And("a browser is launched", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Navigating to Settings triggers cleanup for current feed")]
        [Xunit.TraitAttribute("FeatureTitle", "House-cleaning on Feed Close")]
        [Xunit.TraitAttribute("Description", "Navigating to Settings triggers cleanup for current feed")]
        [Xunit.TraitAttribute("Category", "HouseCleaning")]
        [Xunit.TraitAttribute("Category", "Navigation")]
        public void NavigatingToSettingsTriggersCleanupForCurrentFeed()
        {
            string[] tagsOfScenario = new string[] {
                    "HouseCleaning",
                    "Navigation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigating to Settings triggers cleanup for current feed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 15
        testRunner.Given("the user has created identity \"Alice\" via browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 16
        testRunner.And("Alice has sent 5 messages to their personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 17
        testRunner.And("the localStorage contains messages for the personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 20
        testRunner.When("Alice clicks on the \"new-chat\" navigation item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 23
        testRunner.And("Alice waits for cleanup debounce (200ms)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 24
        testRunner.Then("the cleanupFeed function should have been called", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Switching between feeds triggers cleanup for previous feed")]
        [Xunit.TraitAttribute("FeatureTitle", "House-cleaning on Feed Close")]
        [Xunit.TraitAttribute("Description", "Switching between feeds triggers cleanup for previous feed")]
        [Xunit.TraitAttribute("Category", "HouseCleaning")]
        [Xunit.TraitAttribute("Category", "FeedSwitch")]
        public void SwitchingBetweenFeedsTriggersCleanupForPreviousFeed()
        {
            string[] tagsOfScenario = new string[] {
                    "HouseCleaning",
                    "FeedSwitch"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Switching between feeds triggers cleanup for previous feed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 29
        testRunner.Given("the user has created identity \"Alice\" via browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 30
        testRunner.And("Alice has a chat with \"Bob\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
        testRunner.And("Alice clicks on the chat feed with \"Bob\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 32
        testRunner.And("the transaction is processed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 33
        testRunner.And("Alice sends 3 messages in the chat", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 34
        testRunner.And("the localStorage contains messages for the chat feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 37
        testRunner.When("Alice clicks on their personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 40
        testRunner.And("Alice waits for cleanup debounce (200ms)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 41
        testRunner.Then("the cleanupFeed function should have been called for the chat feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cache is trimmed to limit on feed close")]
        [Xunit.TraitAttribute("FeatureTitle", "House-cleaning on Feed Close")]
        [Xunit.TraitAttribute("Description", "Cache is trimmed to limit on feed close")]
        [Xunit.TraitAttribute("Category", "HouseCleaning")]
        [Xunit.TraitAttribute("Category", "LocalStorage")]
        [Xunit.TraitAttribute("Category", "Slow")]
        public void CacheIsTrimmedToLimitOnFeedClose()
        {
            string[] tagsOfScenario = new string[] {
                    "HouseCleaning",
                    "LocalStorage",
                    "Slow"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cache is trimmed to limit on feed close", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 47
        testRunner.Given("the user has created identity \"Alice\" via browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 48
        testRunner.And("Alice has sent 5 messages to their personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 49
        testRunner.And("the messages are stored in localStorage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 52
        testRunner.When("Alice clicks on the \"new-chat\" navigation item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 53
        testRunner.And("Alice waits for cleanup debounce (200ms)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 54
        testRunner.And("Alice clicks on the \"feeds\" navigation item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 57
        testRunner.Then("the personal feed should load successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 58
        testRunner.And("the messages should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Returning to feed shows messages from bottom")]
        [Xunit.TraitAttribute("FeatureTitle", "House-cleaning on Feed Close")]
        [Xunit.TraitAttribute("Description", "Returning to feed shows messages from bottom")]
        [Xunit.TraitAttribute("Category", "HouseCleaning")]
        [Xunit.TraitAttribute("Category", "ReturnToFeed")]
        public void ReturningToFeedShowsMessagesFromBottom()
        {
            string[] tagsOfScenario = new string[] {
                    "HouseCleaning",
                    "ReturnToFeed"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Returning to feed shows messages from bottom", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 62
        testRunner.Given("the user has created identity \"Alice\" via browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 63
        testRunner.And("Alice has sent 5 messages to their personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 64
        testRunner.And("the messages are visible in the chat", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 67
        testRunner.When("Alice clicks on the \"new-chat\" navigation item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 68
        testRunner.And("Alice waits for cleanup debounce (200ms)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 69
        testRunner.And("Alice clicks on the \"feeds\" navigation item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 70
        testRunner.And("Alice clicks on their personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 73
        testRunner.Then("the most recent message should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 74
        testRunner.And("the chat view should be at the bottom", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Tab close triggers best-effort cleanup")]
        [Xunit.TraitAttribute("FeatureTitle", "House-cleaning on Feed Close")]
        [Xunit.TraitAttribute("Description", "Tab close triggers best-effort cleanup")]
        [Xunit.TraitAttribute("Category", "HouseCleaning")]
        [Xunit.TraitAttribute("Category", "TabClose")]
        [Xunit.TraitAttribute("Category", "Manual")]
        public void TabCloseTriggersBest_EffortCleanup()
        {
            string[] tagsOfScenario = new string[] {
                    "HouseCleaning",
                    "TabClose",
                    "Manual"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Tab close triggers best-effort cleanup", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 77
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 81
        testRunner.Given("the user has created identity \"Alice\" via browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 82
        testRunner.And("Alice has sent 3 messages to their personal feed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 85
        testRunner.When("Alice closes the browser tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 89
        testRunner.Then("the cleanup should have been attempted before unload", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                House_CleaningOnFeedCloseFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                House_CleaningOnFeedCloseFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
