// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HushNode.IntegrationTests.Features.E2E
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "E2E")]
    [Xunit.TraitAttribute("Category", "HushVoting")]
    [Xunit.TraitAttribute("Category", "EPIC-015")]
    [Xunit.TraitAttribute("Category", "FEAT-136")]
    public partial class HushVotingReceiptVerifierFeature : object, Xunit.IClassFixture<HushVotingReceiptVerifierFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "E2E",
                "HushVoting",
                "EPIC-015",
                "FEAT-136"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "HushVotingReceiptVerifierE2E.feature"
#line hidden
        
        public HushVotingReceiptVerifierFeature(HushVotingReceiptVerifierFeature.FixtureData fixtureData, HushNode_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/E2E", "HushVoting Receipt Verifier", "    As a public HushVoting verifier\r\n    I want to verify a receipt against a fin" +
                    "alized package in the browser\r\n    So that receipt inclusion does not depend on " +
                    "the original device or session", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
    #line hidden
#line 8
        testRunner.Given("a HushServerNode at block 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
        testRunner.And("HushWebClient is running in Docker", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
        testRunner.And("a browser is launched", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Public verifier verifies a package-bound receipt against a finalized package ZIP")]
        [Xunit.TraitAttribute("FeatureTitle", "HushVoting Receipt Verifier")]
        [Xunit.TraitAttribute("Description", "Public verifier verifies a package-bound receipt against a finalized package ZIP")]
        [Xunit.TraitAttribute("Category", "HV-E2E-FEAT-136")]
        [Xunit.TraitAttribute("Category", "PR")]
        public void PublicVerifierVerifiesAPackage_BoundReceiptAgainstAFinalizedPackageZIP()
        {
            string[] tagsOfScenario = new string[] {
                    "HV-E2E-FEAT-136",
                    "PR"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Public verifier verifies a package-bound receipt against a finalized package ZIP", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 14
        testRunner.Given("the FEAT-136 package-bound receipt and finalized package ZIP are prepared for the" +
                        " browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 15
        testRunner.When("the public user opens the receipt verifier", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 16
        testRunner.And("the public user imports the FEAT-136 receipt and package ZIP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 17
        testRunner.And("the public user runs receipt verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
        testRunner.Then("the FEAT-136 receipt verifier should show a verified included result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 19
        testRunner.And("the FEAT-136 receipt verifier should not show forbidden private voting data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                HushVotingReceiptVerifierFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                HushVotingReceiptVerifierFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
