// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HushNode.IntegrationTests.HushVoting.Features.Identity_Create
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "HushVoting")]
    [Xunit.TraitAttribute("Category", "HV-IDENTITY-CREATE")]
    [Xunit.TraitAttribute("Category", "HV-FEAT-007")]
    [Xunit.TraitAttribute("Category", "FEAT-007")]
    public partial class IdentityCreateNavigationMulti_OwnerCancellationSecurityNativeFeature : object, Xunit.IClassFixture<IdentityCreateNavigationMulti_OwnerCancellationSecurityNativeFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "HushVoting",
                "HV-IDENTITY-CREATE",
                "HV-FEAT-007",
                "FEAT-007"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "nav-multi-cancel-secure-native.feature"
#line hidden
        
        public IdentityCreateNavigationMulti_OwnerCancellationSecurityNativeFeature(IdentityCreateNavigationMulti_OwnerCancellationSecurityNativeFeature.FixtureData fixtureData, HushNode_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "HushVoting/Features/identity-create", "Identity create — navigation, multi-owner, cancellation, security, native", "  Covers HV-ID-CREATE-NAV, HV-ID-CREATE-MULTI, HV-ID-CREATE-CANCEL,\n  HV-ID-CREAT" +
                    "E-SECURITY, HV-ID-CREATE-NATIVE.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Browser, Android, and in-app Back share one typed authority")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Browser, Android, and in-app Back share one typed authority")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-058")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-NAV-001")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void BrowserAndroidAndIn_AppBackShareOneTypedAuthority()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-058",
                    "HV-ID-CREATE-NAV-001",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Browser, Android, and in-app Back share one typed authority", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
    testRunner.Given("Alice checks both Web Back controls at every unsaved creation screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 12
    testRunner.When("Alice starts creation again after discarding the final candidate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 13
    testRunner.Then("fresh generation was required and no abandoned creation reached the real node", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="After provisional persistence, stale history cannot reopen creation")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "After provisional persistence, stale history cannot reopen creation")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-059")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-NAV-002")]
        [Xunit.TraitAttribute("Category", "HV-ID-LIFECYCLE-MIGRATED")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void AfterProvisionalPersistenceStaleHistoryCannotReopenCreation()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-059",
                    "HV-ID-CREATE-NAV-002",
                    "HV-ID-LIFECYCLE-MIGRATED",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("After provisional persistence, stale history cannot reopen creation", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 17
    testRunner.Given("Alice\'s creation review has a real encrypted provisional vault", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 18
    testRunner.When("Alice navigates Back then Forward and reloads the provisional creation history", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 19
    testRunner.Then("the same provisional keys stay locked until independent registration and a fresh " +
                        "online unlock", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Forged, stale, or restored onboarding tokens are rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Forged, stale, or restored onboarding tokens are rejected")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-060")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-NAV-003")]
        [Xunit.TraitAttribute("Category", "HV-ID-LIFECYCLE-MIGRATED")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void ForgedStaleOrRestoredOnboardingTokensAreRejected()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-060",
                    "HV-ID-CREATE-NAV-003",
                    "HV-ID-LIFECYCLE-MIGRATED",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Forged, stale, or restored onboarding tokens are rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 23
    testRunner.Given("Alice retries rejected creation cleanup before starting a fresh provisional revie" +
                        "w", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 24
    testRunner.When("Alice presents stale and forged creation tokens and manually navigates to a creat" +
                        "ion query", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 25
    testRunner.Then("the same provisional keys stay locked until independent registration and a fresh " +
                        "online unlock", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A non-secret cross-tab event invalidates stale onboarding authorities")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "A non-secret cross-tab event invalidates stale onboarding authorities")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-061")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-MULTI-002")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void ANon_SecretCross_TabEventInvalidatesStaleOnboardingAuthorities()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-061",
                    "HV-ID-CREATE-MULTI-002",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A non-secret cross-tab event invalidates stale onboarding authorities", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 29
    testRunner.Given("another tab commits a local user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 30
    testRunner.When("the non-secret local-user event is observed or vault inspection runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 31
    testRunner.Then("the stale onboarding authority is invalidated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 32
    testRunner.And("no alias, address, transaction, password, mnemonic, or key is broadcast", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Single-owner authority prevents competing candidates")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Single-owner authority prevents competing candidates")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-062")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-MULTI-003")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void Single_OwnerAuthorityPreventsCompetingCandidates()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-062",
                    "HV-ID-CREATE-MULTI-003",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Single-owner authority prevents competing candidates", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 36
    testRunner.Given("two tabs/windows/processes attempt provisioning", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 37
    testRunner.When("ownership is evaluated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 38
    testRunner.Then("only the single owner may provision or submit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 39
    testRunner.And("a second owner cannot create a competing FEAT-007 candidate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Concurrent triggers coalesce into one reconciliation cycle")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Concurrent triggers coalesce into one reconciliation cycle")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-031")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-MULTI-001")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void ConcurrentTriggersCoalesceIntoOneReconciliationCycle()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-031",
                    "HV-ID-CREATE-MULTI-001",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Concurrent triggers coalesce into one reconciliation cycle", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 43
    testRunner.Given("startup, focus, connectivity, and user retry occur together", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 44
    testRunner.When("reconciliation starts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 45
    testRunner.Then("one authority-owned lookup runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 46
    testRunner.And("at most one submission follows authoritative absence", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Pre-submit cancellation verifies rollback before restoring first-run")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Pre-submit cancellation verifies rollback before restoring first-run")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-055")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-CANCEL-001")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void Pre_SubmitCancellationVerifiesRollbackBeforeRestoringFirst_Run()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-055",
                    "HV-ID-CREATE-CANCEL-001",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pre-submit cancellation verifies rollback before restoring first-run", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 49
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 50
    testRunner.Given("no submission has been attempted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 51
    testRunner.When("cancellation is confirmed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 52
    testRunner.Then("rollback is invoked with destructive confirmation and fresh Device-password autho" +
                        "rization", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 53
    testRunner.And("first-run is restored only after storage absence is verified", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Post-submit cancellation warns that blockchain creation cannot be cancelled")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Post-submit cancellation warns that blockchain creation cannot be cancelled")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-056")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-CANCEL-002")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void Post_SubmitCancellationWarnsThatBlockchainCreationCannotBeCancelled()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-056",
                    "HV-ID-CREATE-CANCEL-002",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Post-submit cancellation warns that blockchain creation cannot be cancelled", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 57
    testRunner.Given("a submission may have occurred", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 58
    testRunner.When("local cancellation is confirmed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 59
    testRunner.Then("the warning states the transaction may still confirm and saved recovery words are" +
                        " required to restore", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 60
    testRunner.And("fresh authorization and acknowledgement are required", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Rollback failure quarantines the authority")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Rollback failure quarantines the authority")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-057")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-CANCEL-003")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void RollbackFailureQuarantinesTheAuthority()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-057",
                    "HV-ID-CREATE-CANCEL-003",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Rollback failure quarantines the authority", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 64
    testRunner.Given("rollback cannot verify storage absence", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 65
    testRunner.When("cleanup is evaluated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 66
    testRunner.Then("the authority is quarantined, capabilities revoked, and first-run/authentication " +
                        "blocked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 67
    testRunner.And("tombstone-backed cleanup retries until every slot is verified absent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Secrets never enter React, XState, history, logs, or plaintext storage")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Secrets never enter React, XState, history, logs, or plaintext storage")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-016")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SECURITY-001")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void SecretsNeverEnterReactXStateHistoryLogsOrPlaintextStorage()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-016",
                    "HV-ID-CREATE-SECURITY-001",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Secrets never enter React, XState, history, logs, or plaintext storage", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 71
    testRunner.Given("the creation flow runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 72
    testRunner.When("secrets are handled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 73
    testRunner.Then("private keys and the full phrase never enter React, XState, route/history state, " +
                        "logs, analytics, or persistent plaintext storage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Each platform uses only its sealed operation seams")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Each platform uses only its sealed operation seams")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-024")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SECURITY-002")]
        [Xunit.TraitAttribute("Category", "HV-ID-LIFECYCLE-MIGRATED")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void EachPlatformUsesOnlyItsSealedOperationSeams()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-024",
                    "HV-ID-CREATE-SECURITY-002",
                    "HV-ID-LIFECYCLE-MIGRATED",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Each platform uses only its sealed operation seams", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 76
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 78
    testRunner.Given("Alice protects a Web identity while only public worker operation metadata is obse" +
                        "rved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 79
    testRunner.When("generic signing decryption and private-key export requests reach her real Web wor" +
                        "ker", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 80
    testRunner.Then("the requests produce no result or storage mutation and sealed creation completes " +
                        "real identity and licence indexing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="No social or feed state is initialized during onboarding")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "No social or feed state is initialized during onboarding")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-067")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SECURITY-003")]
        [Xunit.TraitAttribute("Category", "HV-ID-LIFECYCLE-MIGRATED")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void NoSocialOrFeedStateIsInitializedDuringOnboarding()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-067",
                    "HV-ID-CREATE-SECURITY-003",
                    "HV-ID-LIFECYCLE-MIGRATED",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No social or feed state is initialized during onboarding", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 83
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 84
    testRunner.Given("an active reveal authority", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 85
    testRunner.When("Alice protects and registers that generated identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 86
    testRunner.Then("identity onboarding creates no personal feed or social state before the separate " +
                        "licence gate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Secret-bearing scenarios disable capture and artifact scanning finds nothing")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Secret-bearing scenarios disable capture and artifact scanning finds nothing")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-069")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SECURITY-004")]
        [Xunit.TraitAttribute("Category", "HV-ARTIFACT-PRIVACY")]
        [Xunit.TraitAttribute("Category", "HV-ID-LIFECYCLE-MIGRATED")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void Secret_BearingScenariosDisableCaptureAndArtifactScanningFindsNothing()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-069",
                    "HV-ID-CREATE-SECURITY-004",
                    "HV-ARTIFACT-PRIVACY",
                    "HV-ID-LIFECYCLE-MIGRATED",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Secret-bearing scenarios disable capture and artifact scanning finds nothing", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 89
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 90
    testRunner.Given("a scenario that displays recovery words or accepts a password", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 91
    testRunner.When("evidence is collected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 92
    testRunner.Then("trace, screenshot, and video capture are disabled before exposure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 93
    testRunner.And("artifact scanning finds no mnemonic-like sequences, private keys, passwords, or f" +
                        "ull transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Server TwinTests prove rejection and confirmation semantics")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Server TwinTests prove rejection and confirmation semantics")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-071")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SECURITY-005")]
        [Xunit.TraitAttribute("Category", "HV-SERVER-TWIN")]
        [Xunit.TraitAttribute("Category", "NON_E2E")]
        [Xunit.TraitAttribute("Category", "HV-ORIGINAL-IDENTITY-TWIN")]
        public void ServerTwinTestsProveRejectionAndConfirmationSemantics()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-071",
                    "HV-ID-CREATE-SECURITY-005",
                    "HV-SERVER-TWIN",
                    "NON_E2E",
                    "HV-ORIGINAL-IDENTITY-TWIN"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Server TwinTests prove rejection and confirmation semantics", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 96
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 97
    testRunner.Given("a real node process has indexed and cached a P01 private identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 98
    testRunner.When("that node is stopped and its owned chain database and Redis are reset before a ne" +
                        "w node starts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 99
    testRunner.Then("forged recreation is rejected and one fresh same-key transaction restores the exa" +
                        "ct profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Concurrent admission produces exactly one ACCEPTED")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Concurrent admission produces exactly one ACCEPTED")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-072")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SECURITY-006")]
        [Xunit.TraitAttribute("Category", "HV-ID-LIFECYCLE-MIGRATED")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void ConcurrentAdmissionProducesExactlyOneACCEPTED()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-072",
                    "HV-ID-CREATE-SECURITY-006",
                    "HV-ID-LIFECYCLE-MIGRATED",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Concurrent admission produces exactly one ACCEPTED", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 102
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 103
    testRunner.Given("Alice\'s reviewed browser transaction will compete with seven exact retransmission" +
                        "s at the real node", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 104
    testRunner.When("all eight identity RPCs arrive before their admission barrier is released", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 105
    testRunner.Then("the node returns one ACCEPTED and seven PENDING replies for those exact signed by" +
                        "tes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 106
    testRunner.And("Alice retains the same pending keys until identity and licence indexing unlock th" +
                        "e browser shell", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="The fault matrix converges safely")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "The fault matrix converges safely")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-073")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SECURITY-007")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void TheFaultMatrixConvergesSafely()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-073",
                    "HV-ID-CREATE-SECURITY-007",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The fault matrix converges safely", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 109
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 110
    testRunner.Given("fault injection at journal, network, promotion, polling, synchronization, deletio" +
                        "n, and ownership boundaries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 111
    testRunner.When("each interruption occurs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 112
    testRunner.Then("every interruption converges to one safe state", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 113
    testRunner.And("no duplicate candidate/submission, secret exposure, or false authentication occur" +
                        "s", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="The external hardening blocker is green before completion")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "The external hardening blocker is green before completion")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-076")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SECURITY-008")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        [Xunit.TraitAttribute("Category", "HV-BACKEND-RELEASE")]
        public void TheExternalHardeningBlockerIsGreenBeforeCompletion()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-076",
                    "HV-ID-CREATE-SECURITY-008",
                    "HV-E2E",
                    "E2E",
                    "HV-BACKEND-RELEASE"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The external hardening blocker is green before completion", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 116
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 117
    testRunner.Given("the complete HushServerNode signature binding admission status and TwinTest relea" +
                        "se matrix has verified current-build evidence", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 118
    testRunner.When("the real Web missing-profile flow submits its exact signed identity and waits for" +
                        " indexed confirmation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 119
    testRunner.Then("the complete backend prerequisite and this indexed Web journey share the executed" +
                        " build without approving other release gates", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ubuntu uses native custody and never exposes credentials to the WebView")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Ubuntu uses native custody and never exposes credentials to the WebView")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-064")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-NATIVE-001")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void UbuntuUsesNativeCustodyAndNeverExposesCredentialsToTheWebView()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-064",
                    "HV-ID-CREATE-NATIVE-001",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ubuntu uses native custody and never exposes credentials to the WebView", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 122
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 123
    testRunner.Given("a qualified Secret Service or its approved explicit fallback", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 124
    testRunner.When("identity creation runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 125
    testRunner.Then("credentials, signing, and transport remain native", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 126
    testRunner.And("the WebView receives only safe projections", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Android requires hardware-backed protection with no fallback")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Android requires hardware-backed protection with no fallback")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-065")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-NATIVE-002")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void AndroidRequiresHardware_BackedProtectionWithNoFallback()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-065",
                    "HV-ID-CREATE-NATIVE-002",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Android requires hardware-backed protection with no fallback", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 129
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 130
    testRunner.Given("secure lock or qualified hardware-backed Keystore is absent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 131
    testRunner.When("Create User preflight runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 132
    testRunner.Then("generation is blocked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 133
    testRunner.And("no browser, software, or password-only fallback is selected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Adapters observe the same server reply equivalently")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Adapters observe the same server reply equivalently")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-066")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-NATIVE-003")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        [Xunit.TraitAttribute("Category", "HV-WEB-TRANSPORT-CONFORMANCE")]
        public void AdaptersObserveTheSameServerReplyEquivalently()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-066",
                    "HV-ID-CREATE-NATIVE-003",
                    "HV-E2E",
                    "E2E",
                    "HV-WEB-TRANSPORT-CONFORMANCE"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adapters observe the same server reply equivalently", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 136
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 139
    testRunner.Given("Alice can compare real node replies with the production Web BFF and worker", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 140
    testRunner.When("real admission and indexing produce Accepted Pending AlreadyExists and Rejected f" +
                        "or her Web creation requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 141
    testRunner.Then("the Web mappings preserve node fields and require exact lookup and licence indexi" +
                        "ng before authenticated access", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Every acceptance criterion maps to executable Gherkin")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Every acceptance criterion maps to executable Gherkin")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-070")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-NATIVE-004")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void EveryAcceptanceCriterionMapsToExecutableGherkin()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-070",
                    "HV-ID-CREATE-NATIVE-004",
                    "HV-E2E",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Every acceptance criterion maps to executable Gherkin", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 144
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 145
    testRunner.Given("the FEAT-007 acceptance catalog", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 146
    testRunner.When("the coverage manifest validator runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 147
    testRunner.Then("all 76 criteria have executable scenarios", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 148
    testRunner.And("every scenario references known criteria and a declared target", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Release evidence pins immutable digests")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — navigation, multi-owner, cancellation, security, native")]
        [Xunit.TraitAttribute("Description", "Release evidence pins immutable digests")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-075")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-NATIVE-005")]
        [Xunit.TraitAttribute("Category", "HV-E2E")]
        [Xunit.TraitAttribute("Category", "E2E")]
        [Xunit.TraitAttribute("Category", "HV-RELEASE-PINS")]
        public void ReleaseEvidencePinsImmutableDigests()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-075",
                    "HV-ID-CREATE-NATIVE-005",
                    "HV-E2E",
                    "E2E",
                    "HV-RELEASE-PINS"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Release evidence pins immutable digests", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 151
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 153
    testRunner.Given("Alice completes the real creation Web journey for input pin evidence", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 154
    testRunner.When("the exact running build and public contract inputs are recorded by content digest" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 155
    testRunner.Then("the recorded pins match the executed sources builds public corpora dependencies a" +
                        "nd Web handoff definitions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 156
    testRunner.And("input pin integrity does not promote missing qualifications or assert release rea" +
                        "diness", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                IdentityCreateNavigationMulti_OwnerCancellationSecurityNativeFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                IdentityCreateNavigationMulti_OwnerCancellationSecurityNativeFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
