// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HushNode.IntegrationTests.HushVoting.Features.Identity_Create
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "HushVoting")]
    [Xunit.TraitAttribute("Category", "HV-E2E")]
    [Xunit.TraitAttribute("Category", "E2E")]
    [Xunit.TraitAttribute("Category", "HV-IDENTITY-CREATE")]
    [Xunit.TraitAttribute("Category", "HV-FEAT-007")]
    [Xunit.TraitAttribute("Category", "FEAT-007")]
    public partial class IdentityCreateStagingSubmissionConfirmationDelayCorrectionResetFeature : object, Xunit.IClassFixture<IdentityCreateStagingSubmissionConfirmationDelayCorrectionResetFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "HushVoting",
                "HV-E2E",
                "E2E",
                "HV-IDENTITY-CREATE",
                "HV-FEAT-007",
                "FEAT-007"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "stage-submit-confirm-delay.feature"
#line hidden
        
        public IdentityCreateStagingSubmissionConfirmationDelayCorrectionResetFeature(IdentityCreateStagingSubmissionConfirmationDelayCorrectionResetFeature.FixtureData fixtureData, HushNode_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "HushVoting/Features/identity-create", "Identity create — staging, submission, confirmation, delay, correction, reset", "  Covers HV-ID-CREATE-STAGE, HV-ID-CREATE-SUBMIT, HV-ID-CREATE-CONFIRM,\n  HV-ID-C" +
                    "REATE-DELAY, HV-ID-CREATE-CORRECT, HV-ID-CREATE-RESET.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A sealed provisional record precedes any network call")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "A sealed provisional record precedes any network call")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-022")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-STAGE-001")]
        public void ASealedProvisionalRecordPrecedesAnyNetworkCall()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-022",
                    "HV-ID-CREATE-STAGE-001"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A sealed provisional record precedes any network call", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
    testRunner.Given("recovery confirmation and a valid device-password capability", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 12
    testRunner.When("Create Identity is invoked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 13
    testRunner.Then("the credential bundle, separate mnemonic record, reviewed profile, exact signed t" +
                        "ransaction, and digest commit atomically", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 14
    testRunner.And("no network call occurs before read-back verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A provisional identity is never authenticated and blocks first-run")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "A provisional identity is never authenticated and blocks first-run")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-023")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-STAGE-002")]
        [Xunit.TraitAttribute("Category", "HV-ID-SUBMISSION-MIGRATED")]
        public void AProvisionalIdentityIsNeverAuthenticatedAndBlocksFirst_Run()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-023",
                    "HV-ID-CREATE-STAGE-002",
                    "HV-ID-SUBMISSION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A provisional identity is never authenticated and blocks first-run", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 18
    testRunner.Given("Alice\'s creation review has a real encrypted provisional vault", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 19
    testRunner.When("Alice checks the provisional review and then leaves it without submitting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
    testRunner.Then("the same provisional keys stay locked until independent registration and a fresh " +
                        "online unlock", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="The exact signed transaction survives process death")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "The exact signed transaction survives process death")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-027")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-STAGE-003")]
        [Xunit.TraitAttribute("Category", "HV-ID-SUBMISSION-MIGRATED")]
        public void TheExactSignedTransactionSurvivesProcessDeath()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-027",
                    "HV-ID-CREATE-STAGE-003",
                    "HV-ID-SUBMISSION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The exact signed transaction survives process death", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 24
    testRunner.Given("Alice\'s restartable browser has sealed and submitted an identity that is not yet " +
                        "indexed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 25
    testRunner.When("the owned browser process is killed and restarted using its existing encrypted st" +
                        "orage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 26
    testRunner.Then("the exact signed bytes survive and ordinary unlock completes only after real iden" +
                        "tity and licence indexing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Restart with a provisional record resumes safely without mnemonic reveal")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Restart with a provisional record resumes safely without mnemonic reveal")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-052")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-STAGE-004")]
        [Xunit.TraitAttribute("Category", "HV-STAGED-RESUME")]
        public void RestartWithAProvisionalRecordResumesSafelyWithoutMnemonicReveal()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-052",
                    "HV-ID-CREATE-STAGE-004",
                    "HV-STAGED-RESUME"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Restart with a provisional record resumes safely without mnemonic reveal", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 30
    testRunner.Given("Alice has genuinely staged creation in a browser that will lose its process", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 31
    testRunner.When("the browser restarts with only its persistent staged vault and no onboarding auth" +
                        "ority", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 32
    testRunner.Then("the required staged-resume heading appears before password unlock and exact onlin" +
                        "e activation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Promotion failure retries only the local transition")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Promotion failure retries only the local transition")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-054")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-STAGE-005")]
        [Xunit.TraitAttribute("Category", "HV-ID-SUBMISSION-MIGRATED")]
        public void PromotionFailureRetriesOnlyTheLocalTransition()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-054",
                    "HV-ID-CREATE-STAGE-005",
                    "HV-ID-SUBMISSION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Promotion failure retries only the local transition", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 36
    testRunner.Given("Alice has a real accepted identity and the next local lifecycle commit will abort" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 37
    testRunner.When("the real worker journal commit aborts and Alice retries only the local save", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 38
    testRunner.Then("the preserved identity becomes active without resubmission and real licence index" +
                        "ing opens the workspace", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="The transaction is canonical")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "The transaction is canonical")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-025")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SUBMIT-001")]
        [Xunit.TraitAttribute("Category", "HV-ID-SUBMISSION-MIGRATED")]
        public void TheTransactionIsCanonical()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-025",
                    "HV-ID-CREATE-SUBMIT-001",
                    "HV-ID-SUBMISSION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The transaction is canonical", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 42
    testRunner.Given("reviewed profile fields and exact candidate addresses", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 43
    testRunner.When("the signed transaction is constructed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 44
    testRunner.Then("it uses CSPRNG UUIDv4, a corpus-exact UTC timestamp, approved property order, exa" +
                        "ct UTF-8 PayloadSize, the exact payload GUID, and the established signed JSON re" +
                        "presentation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Signatory, payload signing address, and signing key bind exactly")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Signatory, payload signing address, and signing key bind exactly")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-026")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SUBMIT-002")]
        [Xunit.TraitAttribute("Category", "HV-ID-SUBMISSION-MIGRATED")]
        public void SignatoryPayloadSigningAddressAndSigningKeyBindExactly()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-026",
                    "HV-ID-CREATE-SUBMIT-002",
                    "HV-ID-SUBMISSION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Signatory, payload signing address, and signing key bind exactly", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 48
    testRunner.Given("the authority owns the signing key", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 49
    testRunner.When("the transaction is signed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 50
    testRunner.Then("UserSignature.Signatory equals the payload signing address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 51
    testRunner.And("both equal the authority-owned signing key", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Every cycle performs GetIdentity before submission")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Every cycle performs GetIdentity before submission")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-028")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SUBMIT-003")]
        [Xunit.TraitAttribute("Category", "HV-ID-SUBMISSION-MIGRATED")]
        public void EveryCyclePerformsGetIdentityBeforeSubmission()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-028",
                    "HV-ID-CREATE-SUBMIT-003",
                    "HV-ID-SUBMISSION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Every cycle performs GetIdentity before submission", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 55
    testRunner.Given("Alice has approved creation review but has not queried or submitted the new ident" +
                        "ity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 56
    testRunner.When("Alice creates the identity and later restarts before its first authenticated unlo" +
                        "ck", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 57
    testRunner.Then("initial admission and restart both query the exact public address before any subs" +
                        "equent transaction", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Only authoritative absence permits submission")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Only authoritative absence permits submission")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-029")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SUBMIT-004")]
        [Xunit.TraitAttribute("Category", "HV-ID-SUBMISSION-MIGRATED")]
        public void OnlyAuthoritativeAbsencePermitsSubmission()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-029",
                    "HV-ID-CREATE-SUBMIT-004",
                    "HV-ID-SUBMISSION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Only authoritative absence permits submission", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 61
    testRunner.Given("Alice has approved creation review but has not queried or submitted the new ident" +
                        "ity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 62
    testRunner.When("Alice requests creation while the real initial identity lookup is unavailable", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 63
    testRunner.Then("no transaction is submitted until explicit Retry obtains authoritative absence fr" +
                        "om the node", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Exact keys confirm the same identity; encryption mismatch fails closed")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Exact keys confirm the same identity; encryption mismatch fails closed")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-030")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SUBMIT-005")]
        [Xunit.TraitAttribute("Category", "HV-ID-SUBMISSION-MIGRATED")]
        public void ExactKeysConfirmTheSameIdentityEncryptionMismatchFailsClosed()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-030",
                    "HV-ID-CREATE-SUBMIT-005",
                    "HV-ID-SUBMISSION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Exact keys confirm the same identity; encryption mismatch fails closed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 66
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 67
    testRunner.Given("Alice has approved creation review but has not queried or submitted the new ident" +
                        "ity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 68
    testRunner.When("a real indexed profile has Alice\'s signing address but a different encryption add" +
                        "ress", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 69
    testRunner.Then("creation fails closed without submitting or activating that mismatched identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 70
    testRunner.And("a fresh candidate with both keys already indexed completes without recreating its" +
                        " identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ACCEPTED promotes to saved-waiting without claiming confirmation")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "ACCEPTED promotes to saved-waiting without claiming confirmation")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-032")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SUBMIT-006")]
        [Xunit.TraitAttribute("Category", "HV-ID-WAITING-LIFECYCLE")]
        [Xunit.TraitAttribute("Category", "HV-ID-SUBMISSION-MIGRATED")]
        public void ACCEPTEDPromotesToSaved_WaitingWithoutClaimingConfirmation()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-032",
                    "HV-ID-CREATE-SUBMIT-006",
                    "HV-ID-WAITING-LIFECYCLE",
                    "HV-ID-SUBMISSION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ACCEPTED promotes to saved-waiting without claiming confirmation", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 73
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 74
    testRunner.Given("submission returns ACCEPTED", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 75
    testRunner.When("the lifecycle is promoted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 76
    testRunner.Then("the provisional lifecycle becomes saved-user waiting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 77
    testRunner.And("no block confirmation is claimed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="PENDING waits without another submission")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "PENDING waits without another submission")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-033")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SUBMIT-007")]
        [Xunit.TraitAttribute("Category", "HV-ID-WAITING-LIFECYCLE")]
        [Xunit.TraitAttribute("Category", "HV-ID-SUBMISSION-MIGRATED")]
        public void PENDINGWaitsWithoutAnotherSubmission()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-033",
                    "HV-ID-CREATE-SUBMIT-007",
                    "HV-ID-WAITING-LIFECYCLE",
                    "HV-ID-SUBMISSION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PENDING waits without another submission", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 80
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 81
    testRunner.Given("Alice\'s reviewed identity is ready for controlled duplicate delivery of its exact" +
                        " transaction", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 82
    testRunner.When("Alice submits through the browser and the node responds PENDING for the same sign" +
                        "ing key", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 83
    testRunner.Then("HushVoting retains a saved waiting identity after the genuine PENDING reply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 84
    testRunner.And("polling preserves those exact bytes without another submission until real block c" +
                        "onfirmation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ALREADY_EXISTS resolves by exact lookup only")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "ALREADY_EXISTS resolves by exact lookup only")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-034")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SUBMIT-008")]
        [Xunit.TraitAttribute("Category", "HV-ID-EXACT-CONFIRMATION")]
        [Xunit.TraitAttribute("Category", "HV-ID-SUBMISSION-MIGRATED")]
        public void ALREADY_EXISTSResolvesByExactLookupOnly()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-034",
                    "HV-ID-CREATE-SUBMIT-008",
                    "HV-ID-EXACT-CONFIRMATION",
                    "HV-ID-SUBMISSION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ALREADY_EXISTS resolves by exact lookup only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 87
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 88
    testRunner.Given("Alice has reviewed a Private identity and its first submission can be delayed bef" +
                        "ore admission", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 89
    testRunner.When("another device indexes the same keys with a different Public profile before Alice" +
                        "\'s delayed submission completes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 90
    testRunner.Then("fresh exact indexed lookup is required after the real ALREADY_EXISTS response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 91
    testRunner.And("authenticated access follows exact identity verification and separate licence ind" +
                        "exing without another identity submission", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Status/code combinations use a closed allowlist")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Status/code combinations use a closed allowlist")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-035")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SUBMIT-009")]
        [Xunit.TraitAttribute("Category", "HV-ID-CONFIRMATION-MIGRATED")]
        public void StatusCodeCombinationsUseAClosedAllowlist()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-035",
                    "HV-ID-CREATE-SUBMIT-009",
                    "HV-ID-CONFIRMATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Status/code combinations use a closed allowlist", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 94
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 95
    testRunner.Given("Alice can submit a reviewed identity to the real node with a negative reply obser" +
                        "ver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 96
    testRunner.When("real submission replies are made contradictory unknown or unspecified", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 97
    testRunner.Then("invalid replies cannot admit or retry while an ordinary reply completes indexed i" +
                        "dentity and licence verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Transport ambiguity preserves the exact transaction")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Transport ambiguity preserves the exact transaction")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-036")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SUBMIT-010")]
        [Xunit.TraitAttribute("Category", "HV-ID-LOST-RESPONSE")]
        [Xunit.TraitAttribute("Category", "HV-ID-CONFIRMATION-MIGRATED")]
        public void TransportAmbiguityPreservesTheExactTransaction()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-036",
                    "HV-ID-CREATE-SUBMIT-010",
                    "HV-ID-LOST-RESPONSE",
                    "HV-ID-CONFIRMATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Transport ambiguity preserves the exact transaction", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 100
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 101
    testRunner.Given("Alice\'s identity is accepted by the real node but its submission response is lost" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 102
    testRunner.When("Alice retries the ambiguous connection before the identity is indexed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 103
    testRunner.Then("the encrypted pending identity retains the exact signed transaction and digest wi" +
                        "thout replacement", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 104
    testRunner.And("real identity and licence indexing complete access without another identity trans" +
                        "action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ambiguous retries reuse exact signed bytes")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Ambiguous retries reuse exact signed bytes")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-045")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SUBMIT-011")]
        [Xunit.TraitAttribute("Category", "HV-ID-CONFIRMATION-MIGRATED")]
        public void AmbiguousRetriesReuseExactSignedBytes()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-045",
                    "HV-ID-CREATE-SUBMIT-011",
                    "HV-ID-CONFIRMATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ambiguous retries reuse exact signed bytes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 107
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 108
    testRunner.Given("Alice loses a real accepted response while a public sealed submission command is " +
                        "observed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 109
    testRunner.When("her actual Web worker retries the sealed transaction after lookup confirms absenc" +
                        "e", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 110
    testRunner.Then("the real node returns PENDING for identical bytes and normal confirmation indexes" +
                        " one identity and its licence", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A missing transaction can be rebuilt only after verified eligibility")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "A missing transaction can be rebuilt only after verified eligibility")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-048")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SUBMIT-012")]
        public void AMissingTransactionCanBeRebuiltOnlyAfterVerifiedEligibility()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-048",
                    "HV-ID-CREATE-SUBMIT-012"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A missing transaction can be rebuilt only after verified eligibility", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 113
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 114
    testRunner.Given("the retained transaction record is missing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 115
    testRunner.When("rebuild eligibility is evaluated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 116
    testRunner.Then("authenticated credential/profile verification AND authoritative absence are both " +
                        "required", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 117
    testRunner.And("corruption never counts as missing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="The client never polls as retry or periodically replaces transactions")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "The client never polls as retry or periodically replaces transactions")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-050")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-SUBMIT-013")]
        [Xunit.TraitAttribute("Category", "HV-ID-CONFIRMATION-MIGRATED")]
        public void TheClientNeverPollsAsRetryOrPeriodicallyReplacesTransactions()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-050",
                    "HV-ID-CREATE-SUBMIT-013",
                    "HV-ID-CONFIRMATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The client never polls as retry or periodically replaces transactions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 120
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 121
    testRunner.Given("the waiting gate is active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 122
    testRunner.When("time passes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 123
    testRunner.Then("no submission occurs every three seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 124
    testRunner.And("no periodic replacement or liveness submission is implemented", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="The waiting gate is accessible and explicit")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "The waiting gate is accessible and explicit")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-037")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-CONFIRM-001")]
        [Xunit.TraitAttribute("Category", "HV-ID-CONFIRMATION-MIGRATED")]
        public void TheWaitingGateIsAccessibleAndExplicit()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-037",
                    "HV-ID-CREATE-CONFIRM-001",
                    "HV-ID-CONFIRMATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The waiting gate is accessible and explicit", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 127
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 128
    testRunner.Given("the transaction is accepted or pending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 129
    testRunner.When("the confirmation gate renders", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 130
    testRunner.Then("it states that mempool admission is not block confirmation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 131
    testRunner.And("it offers safe Lock/close guidance without an endless unexplained spinner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GetIdentity polls every three seconds while eligible")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "GetIdentity polls every three seconds while eligible")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-038")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-CONFIRM-002")]
        [Xunit.TraitAttribute("Category", "HV-ID-CONFIRMATION-MIGRATED")]
        public void GetIdentityPollsEveryThreeSecondsWhileEligible()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-038",
                    "HV-ID-CREATE-CONFIRM-002",
                    "HV-ID-CONFIRMATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetIdentity polls every three seconds while eligible", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 134
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 135
    testRunner.Given("the waiting gate is foregrounded, online, visible, and authority-valid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 136
    testRunner.When("polling runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 137
    testRunner.Then("GetIdentity is called every three seconds through one coalesced loop", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 138
    testRunner.And("submission never happens on a poll", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 139
    testRunner.And("indexed identity confirmation automatically advances to the root licence gate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Polling pauses on background, offline, Lock, or revocation")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Polling pauses on background, offline, Lock, or revocation")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-039")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-CONFIRM-003")]
        [Xunit.TraitAttribute("Category", "HV-ID-CONFIRMATION-MIGRATED")]
        public void PollingPausesOnBackgroundOfflineLockOrRevocation()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-039",
                    "HV-ID-CREATE-CONFIRM-003",
                    "HV-ID-CONFIRMATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Polling pauses on background, offline, Lock, or revocation", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 142
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 143
    testRunner.Given("Alice\'s unindexed browser identity has an active real three-second confirmation l" +
                        "oop", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 144
    testRunner.When("the waiting page receives a controlled visibility loss and recovery then goes off" +
                        "line and online", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 145
    testRunner.Then("resumed confirmation polls issue no worker operations or user-input events", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 146
    testRunner.And("Lock revokes the waiting authority and stops its RPCs until fresh unlock after re" +
                        "al indexing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Check again performs lookup only")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Check again performs lookup only")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-040")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-CONFIRM-004")]
        [Xunit.TraitAttribute("Category", "HV-ID-CONFIRMATION-MIGRATED")]
        public void CheckAgainPerformsLookupOnly()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-040",
                    "HV-ID-CREATE-CONFIRM-004",
                    "HV-ID-CONFIRMATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check again performs lookup only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 149
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 150
    testRunner.Given("the waiting gate with a Check again control", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 151
    testRunner.When("the user selects Check again", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 152
    testRunner.Then("one immediate coalesced lookup runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 153
    testRunner.And("no new poll loop or submission is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Exact confirmation synchronizes and clears")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Exact confirmation synchronizes and clears")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-042")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-CONFIRM-005")]
        [Xunit.TraitAttribute("Category", "HV-ID-EXACT-CONFIRMATION")]
        [Xunit.TraitAttribute("Category", "HV-ID-CONFIRMATION-MIGRATED")]
        public void ExactConfirmationSynchronizesAndClears()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-042",
                    "HV-ID-CREATE-CONFIRM-005",
                    "HV-ID-EXACT-CONFIRMATION",
                    "HV-ID-CONFIRMATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Exact confirmation synchronizes and clears", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 156
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 157
    testRunner.Given("Alice has reviewed a Private identity and its first submission can be delayed bef" +
                        "ore admission", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 158
    testRunner.When("another device indexes the same keys with a different Public profile before Alice" +
                        "\'s delayed submission completes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 159
    testRunner.Then("the active encrypted record atomically adopts the indexed alias and visibility an" +
                        "d clears its pending transaction", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 160
    testRunner.And("authenticated access follows exact identity verification and separate licence ind" +
                        "exing without another identity submission", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A revoked, expired, or restarted authority requires ordinary unlock")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "A revoked, expired, or restarted authority requires ordinary unlock")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-043")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-CONFIRM-006")]
        public void ARevokedExpiredOrRestartedAuthorityRequiresOrdinaryUnlock()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-043",
                    "HV-ID-CREATE-CONFIRM-006"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A revoked, expired, or restarted authority requires ordinary unlock", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 163
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 164
    testRunner.Given("confirmation occurred but the authority is revoked, expired, backgrounded, or res" +
                        "tarted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 165
    testRunner.When("authentication is evaluated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 166
    testRunner.Then("ordinary unlock is required before entering HushVoting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Mempool acceptance alone never enters the authenticated shell")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Mempool acceptance alone never enters the authenticated shell")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-044")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-CONFIRM-007")]
        [Xunit.TraitAttribute("Category", "HV-ID-CONFIRMATION-MIGRATED")]
        public void MempoolAcceptanceAloneNeverEntersTheAuthenticatedShell()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-044",
                    "HV-ID-CREATE-CONFIRM-007",
                    "HV-ID-CONFIRMATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Mempool acceptance alone never enters the authenticated shell", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 169
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 170
    testRunner.Given("only ACCEPTED or PENDING knowledge exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 171
    testRunner.When("the shell entry is evaluated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 172
    testRunner.Then("HushVoting does not enter the authenticated shell", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 173
    testRunner.And("exact GetIdentity confirmation is required", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A lost acceptance response converges without another identity")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "A lost acceptance response converges without another identity")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-053")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-CONFIRM-008")]
        [Xunit.TraitAttribute("Category", "HV-ID-LOST-RESPONSE")]
        [Xunit.TraitAttribute("Category", "HV-ID-CONFIRMATION-MIGRATED")]
        public void ALostAcceptanceResponseConvergesWithoutAnotherIdentity()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-053",
                    "HV-ID-CREATE-CONFIRM-008",
                    "HV-ID-LOST-RESPONSE",
                    "HV-ID-CONFIRMATION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A lost acceptance response converges without another identity", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 176
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 177
    testRunner.Given("Alice\'s identity is accepted by the real node but its submission response is lost" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 178
    testRunner.When("the accepted identity indexes before Alice retries the lost response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 179
    testRunner.Then("fresh exact lookup and separate licence indexing restore access with only the ori" +
                        "ginal identity transaction", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Three minutes without confirmation enters the delay state")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Three minutes without confirmation enters the delay state")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-041")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-DELAY-001")]
        [Xunit.TraitAttribute("Category", "HV-ID-DELAY-MIGRATED")]
        public void ThreeMinutesWithoutConfirmationEntersTheDelayState()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-041",
                    "HV-ID-CREATE-DELAY-001",
                    "HV-ID-DELAY-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Three minutes without confirmation enters the delay state", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 182
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 183
    testRunner.Given("Alice\'s accepted identity remains unindexed with its exact transaction sealed on " +
                        "the device", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 184
    testRunner.When("three real minutes elapse without producing an identity block", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 185
    testRunner.Then("the delayed screen stops automatic RPCs and retains the sealed vault while Check " +
                        "again remains lookup-only", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 186
    testRunner.And("a manual exact check after real identity indexing completes only through separate" +
                        " licence indexing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Editable alias rejection reopens Profile only")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Editable alias rejection reopens Profile only")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-046")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-CORRECT-001")]
        public void EditableAliasRejectionReopensProfileOnly()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-046",
                    "HV-ID-CREATE-CORRECT-001"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Editable alias rejection reopens Profile only", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 189
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 190
    testRunner.Given("an allowlisted editable pre-admission code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 191
    testRunner.When("correction runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 192
    testRunner.Then("only Profile/Review reopens with the same identity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 193
    testRunner.And("a fresh Device-password authorization is required before one new replacement tran" +
                        "saction", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cryptographic and unknown rejections fail closed without retry")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Cryptographic and unknown rejections fail closed without retry")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-047")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-CORRECT-002")]
        [Xunit.TraitAttribute("Category", "HV-ID-REJECTION-MIGRATED")]
        public void CryptographicAndUnknownRejectionsFailClosedWithoutRetry()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-047",
                    "HV-ID-CREATE-CORRECT-002",
                    "HV-ID-REJECTION-MIGRATED"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cryptographic and unknown rejections fail closed without retry", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 196
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 197
    testRunner.Given("Alice can submit a reviewed identity to the real node with a negative reply obser" +
                        "ver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 198
    testRunner.When("real node signature rejections carry every terminal code and an unknown code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 199
    testRunner.Then("terminal rejection codes cannot retry or leak diagnostics and a fresh explicit id" +
                        "entity completes indexing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Blockchain reset re-registers the same identity")]
        [Xunit.TraitAttribute("FeatureTitle", "Identity create — staging, submission, confirmation, delay, correction, reset")]
        [Xunit.TraitAttribute("Description", "Blockchain reset re-registers the same identity")]
        [Xunit.TraitAttribute("Category", "FEAT-007")]
        [Xunit.TraitAttribute("Category", "AC-007-049")]
        [Xunit.TraitAttribute("Category", "HV-ID-CREATE-RESET-001")]
        public void BlockchainResetRe_RegistersTheSameIdentity()
        {
            string[] tagsOfScenario = new string[] {
                    "FEAT-007",
                    "AC-007-049",
                    "HV-ID-CREATE-RESET-001"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Blockchain reset re-registers the same identity", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 202
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 203
    testRunner.Given("a previously confirmed local identity is authoritatively absent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 204
    testRunner.When("reconciliation completes credential/profile verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 205
    testRunner.Then("one fresh transaction is created from the same vault identity and latest verified" +
                        " encrypted profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 206
    testRunner.And("no new recovery words are generated because the chain was reset", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                IdentityCreateStagingSubmissionConfirmationDelayCorrectionResetFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                IdentityCreateStagingSubmissionConfirmationDelayCorrectionResetFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
